### ISSUE TITLE
SimulationTimeCondition small value doesn't trigger

### ISSUE THREAD

**Issue by wxtshr001** [esmini/esmini#29] opened 2020-07-16 03:05 UTC
When I set a `<SimulationTimeCondition value="0" rule="greaterThan"/>` for an event, the event would not be triggered. And for diffferent scenarios the value works different. 

For example, the lane_change.xosc scenario, the lane change action would not act if SimulationTimeCondition value is less than 0.2. For my own scenario, the action would not act if SimulationTimeCondition value is less than 0.12. That's confusing.

And, line 259 in OSCCondition.hpp,
`TrigBySimulationTime() : TrigByValue(TrigByValue::Type::TIME_OF_DAY) {}`
The type is supposed to be SIMULATION_TIME, is it?

**Comment by eknabevcc** [comment] 2020-07-16 05:26
Thanks for input! 

The delayed trigger is a bit tricky. I'll look into it later, and hopefully being able to either fix or explain. So we'll get back on this.

The condition type bug is clearly a mistake, fixed immediately ([commit d21c643](https://github.com/esmini/esmini/commit/d21c643e04483f84a9fef0565a2e430495cbed5f)).

**Comment by eknabevcc** [comment] 2020-07-16 06:08
If possible, please try to build and test branch "issue_29". It includes an attempt to evaluate act state transitions earlier to avoid the "one-step" delay. I'm not sure if it solves the issue, and if there are side effects. So I put it in a branch so we can test it somewhat first.
Here's the initial commit: https://github.com/esmini/esmini/commits/issue_29

**Comment by wxtshr001** [comment] 2020-07-16 09:01
@eknabevcc Thanks for your reply. I tried the new branch with lane_change.xosc scenario, it worked but not complete. It still not trigger if I set SimulationTimeCondition value less than 0.1

**Comment by wxtshr001** [comment] 2020-07-16 09:07
And when I set the value 0.1, it worked and part of the LOG is as follow:

OSCCondition.cpp / 337 / CheckCondition(): CutInActStart == true, sim_time: 0.1000 > 0.00 edge: RisingOrFalling
OSCAction.cpp / 96 / SetState(): Lane change standbyState -> startTransition -> runningState
OSCCondition.cpp / 337 / CheckCondition(): Lane change == true, sim_time: 0.1950 > 0.10 edge: Rising
OSCAction.cpp / 96 / SetState(): Lane change standbyState -> startTransition -> runningState
OSCAction.cpp / 96 / SetState(): Lane change standbyState -> startTransition -> runningState
OSCAction.hpp / 125 / End(): Lane change complete after 1 execution
OSCAction.cpp / 96 / SetState(): Lane change runningState -> endTransition -> completeState
OSCAction.hpp / 125 / End(): Lane change complete after 1 execution
OSCAction.hpp / 125 / End(): Lane change complete after 1 execution
OSCAction.cpp / 96 / SetState(): Lane change runningState -> endTransition -> completeState
OSCCondition.cpp / 153 / Evaluate(): Timer 4.00s started
OSCCondition.cpp / 337 / CheckCondition(): Lane change == true, sim_time: 3.0130 > 3.00 edge: Rising
OSCAction.cpp / 96 / SetState(): Lane change standbyState -> startTransition -> runningState
OSCAction.cpp / 96 / SetState(): Lane change standbyState -> startTransition -> runningState
playerbase.cpp / 239 / ViewerFrame(): Quit requested from viewer - probably ESC button pressed
ScenarioEngine.cpp / 54 / ~ScenarioEngine(): Closing

**Comment by eknabevcc** [comment] 2020-07-16 12:02
Thanks for clear explanation. I understand the problem now and I will try to explain what happens. In the following pseudo scenario I use time step = 1 ms, but it isn't significant.

First frame (time == 0.000):
    act condition is evaluated to false (time is not greater than 0.000)
Second frame (time == 0.001):
    act condition is evaluated to true (time is greater than 0.000), edge == rising, act is started
    event condition is evaluated to true (but since no previous evaluation edge is undefined)
Third frame (time == 0.002):
    event condition is evaluated to true (but since previous evaluation also true no edge, and hence no trigger)

So the problem is in the second frame where edge is not defined. The root cause is that esmini is lazy and will only evaluate conditions of active parent story board elements. In other words, the event start condition is not evaluated until the act has been started.

One solution would be to always evaluate conditions, regardless of parent storyboard element activated or not, in order to always have a previous state for edge determination (except the very first frame where there simply are no previous states). But there would still be a potential problem if a condition evaluates to true before the parent act has been trigged: Then the rising edge would be missed and trigger would not launch. And I suspect there will be other situations where early evaluation of "previous state" could lead to unexpected results, but I'm not sure to be honest. We need to think more about this interesting topic before implementing a new strategy.

Meanwhile, may I suggest a more stable solution in the case of simulation time condition: Skip edge by specifying NONE (conditionEdge="none"). This means that as soon as the condition evaluates to true (simulation time > 0) then the trigger will launch, regardless of any previous evaluations. Would that work for you, short term?

**Comment by wxtshr001** [comment] 2020-07-17 01:48
@eknabevcc I almost understand your description. But as I see, the condtion checkEdge function compare the new value and old value. The old value(last_result_) is initialized to false in OSCCondtion class initialization. So the evaluation edge is defined as false as previous state and RISING edge would work? That's just my two cents, I don't know whether correctly.

And another question, why the simulation time is 0.195 not 0.11 as the step dt is 0.01? and why the workable time is 0.1?
> OSCCondition.cpp / 337 / CheckCondition(): Lane change == true, sim_time: 0.1950 > 0.10 edge: Rising

**Comment by eknabevcc** [comment] 2020-07-17 05:27
There is an additional flag (evaluated_) to indicate whether the condition has been previously evaluated or not. That flag will prevent edge if the condition has not been evaluated previously. Only edge == none will work at first evaluation. 

Actually, older versions of esmini had an exception for simulation time condition (which I personally found useful), where the flag was simply ignored. But after the release of OpenSCENARIO 1.0 it was clarified that the edge should be undefined first time the condition is checked. Here's an excerpt from the [user guide](https://releases.asam.net/OpenSCENARIO/1.0.0/ASAM_OpenSCENARIO_BS-1-2_User-Guide_V1-0-0.html):

> If the parameter risingEdge is set to rising, falling, or risingOrFalling, a Condition is not defined the first time it is checked since the previous evaluation of the logical expression is not defined. To address this, it is expected that all Conditions defined with rising, falling, or risingOrFalling, return false the first time they are checked by a simulation engine.

So esmini was adjusted accordingly, to prevent confusion of different results from different tools. But you're right, the last_result_ variable is initialized to false. And that had a meaning for the old simulation time exception. But nowadays I think the initialization has no actual effect since the evaluated_ flag is used for all conditions. 

Now, your question regarding simulation time is very interesting. I totally agree that sim time 0.195 should not be possible with timestep 0.01. **Would it be possible for you to share the scenario file** to simplify analysis? Also for you last question, why 0.1 seems to be a magic workable time threshold, it would help to have the actual scenario at hand.

Thanks again for sharing and explaining the issue.

**Comment by wxtshr001** [comment] 2020-07-20 01:37
@eknabevcc Very sorry for late reply. I tested just on the demo scenario esmini provided,  and the path is esmini/resources/xosc/lane_change.xosc. For the master branch the workable time is 0.2, and for issue_29 branch is 0.1

Also I noticed the quoting:

> it is expected that all Conditions defined with rising, falling, or risingOrFalling, **return false the first time they are checked** by a simulation engine

And esmini is likely to followed the standard. But if so, the problem does't make sense. Since the value is false for the first time checked, in next step the RISING edge is supposed to trigger.

**Comment by eknabevcc** [comment] 2020-07-20 08:07
Thanks. I checked the lane_change.xosc. And to make analysis easier I did some updates of storyboard element names. I also did one single adjustment for purpose of the test: For the Target lane change event I changed simulation time value from 3 to 0.01, like this:
<SimulationTimeCondition value="0.01" rule="greaterThan"/>

Then for the actual test I used the ScenarioViewer with TIME_STEP 0.01 (EgoSimulator with --fixed_timestep 0.01 gives same result). This is the result (just focusing on the Target vehicle):

> OSCCondition.cpp / 337 / scenarioengine::TrigBySimulationTime::CheckCondition(): CutInActStart == true, sim_time: 0.0100 > 0.00 edge: RisingOrFalling
> OSCAction.cpp / 96 / scenarioengine::StoryBoardElement::SetState(): Lane change act standbyState -> startTransition -> runningState
> OSCCondition.cpp / 337 / scenarioengine::TrigBySimulationTime::CheckCondition(): Lane change Target condition == true, sim_time: 0.0200 > 0.01 edge: Rising
> OSCAction.cpp / 96 / scenarioengine::StoryBoardElement::SetState(): Lane change Target action standbyState -> startTransition -> runningState
> OSCAction.cpp / 96 / scenarioengine::StoryBoardElement::SetState(): Lane change Target event standbyState -> startTransition -> runningState
> 

I think it is OK and as expected. This is what I assume happens under the hood:
1. Time == 0.00: 
Since Time is not greater than 0.00 the act is not started.
Event condition is not evaluated, since the act hasn't started yet.
2. Time == 0.01: 
Time is now > 0.0, Act is started. 
Time is not greater than 0.01, so the event is not started
3. Time == 0.02:
Time is now > 0.01 (with rising edge). Event is started.

(if event condition simulation time is changed to 0.00, then the event is not launched because the first evaluation, at time 0.01, is true and hence edge is missed. I think this is as expected).

If you use floating time steps, for example running EgoSimulator without the --fixed_timestep argument, then the result is more unpredictable. Let's say that the event start time is 0.02 and the act is started at 0.1 (e.g. due to a slow first frame), then the edge is missed since the first and all succeeding tests will be true (time > 0.02). So I think edge = none makes sense for simulation time conditions.

By the way, I have not been able to reproduce the strange "0.195" case, with a timestamp off fixed timestep multiplier.

As far as I understand, now esmini is behaving as expected, including finding edges when conditions are switching value. Please indicate if you still see a problem. 

Anyway, I have commit the modification so that act state is updated immediately. I think this is an improvement and I can't see any negative side effects. So thanks for reporting this issue and supporting the analysis.

**Comment by wxtshr001** [comment] 2020-07-21 02:44
Thanks for your remind! I didn't add --fixed_timestep parameter,  that's the reason why values less than 0.1 is unworkable. After I added it as 0.01, the workable time is 0.01.
And, I don't think if event condition simulation time changed to 0.00, then the event would not be launched is expected. As you mentioned above, **it is expected that all Conditions defined with rising, falling, or risingOrFalling, return false the first time they are checked by a simulation engine** The event should trigger as the act since the act trigger is also SimulationTimeCondition and value is 0 which works successfully.

**Comment by wxtshr001** [comment] 2020-07-21 02:58
Thanks for you remind! I didn't add --fixed_timestep before. Maybe that's the reason why the workable time is 0.1. After I add the argument as 0.01, the workable time is also 0.01.

And, I don't think if event condition simulation time is changed to 0.00, then the event is not launched is expected. As I mentioned above from ASAM userguide, **it is expected that all Conditions defined with rising, falling, or risingOrFalling, return false the first time they are checked by a simulation engine**. The first test should be false so the RISING edge work but for the event currently not.

**Comment by eknabevcc** [comment] 2020-07-23 06:18
Good, so now remaining issue is that the event is not triggered for condition simulation time = 0.00. 
As discussed previously, event conditions are not evaluated until its parent act has started. And since the act is started at time == 0.01, this is when the event condition is first checked. Now, if condition SimTime is 0.00, then all evaluations will be true, i.e. the edge clearly has been missed. But if SimTime is 0.01 or above, then the first evaluation at 0.01 will be false, and the succeeding one true - so the edge is perfectly detected.
I think this behavior is OK. Potentially, as also discussed, it could be considered to always evaluate all conditions, even of acts that's not active (started) - which would solve this particular SimTime=0.00 case. But that's a bit brute force (leading to many useless calculations) and still I'm not sure if it helps a lot, except for the SimTime = 0 thing. In general it can be hard to hit the event condition edge exactly since the parent act would need to be started at exact the next time step. 
I still think that the edge = none is more convenient for many cases. Edges are useful for situations where you need to consider the derivative, e.g. distance is increasing or decreasing. Let's say you want to trig a lane change when distance between two vehicles is less then X meter, but only when the distance is decreasing from > X.
Well, sorry for long answer. I just want to make sure we have the same understanding.
Do I understand correctly that you would expect the event condition to be evaluated already before act is started? In that case I think we should simply conclude that esmini is not currently behaving like that. But it's a good suggestion and I will bring the question to OpenSCENARIO 1.X project. I think it could be clarified in the standard whether conditions should be checked always or only when parent storyboard elements is active.

**Comment by wxtshr001** [comment] 2020-07-24 02:19
I think the point is, the first time condition is checked/evaluated, it should be defined as false, but not undefined or any other. Currently for value 0 esmini would work as following flow:

> Initialization. result, last_result_ and evaluated_ are false;
> Check condition. If sim time greater than value, result is true;
> Check edge. Because evaluate_ is false, the trig is false;
> last_result_ = result = true;
> evaluated_ = true.

In the next evaluation, the flow is:

> Check condition. Sim time greater than value, result is true;
> Check edge. Because evaluate_ is true, result == last_result_ == true, No RISING, trig = false;
> last_result_ = result = true;
> evaluated_ = true.

In the above flow, you can see the reason which makes the RISING edge missing for value 0 is that in the first evaluation, the result is defined as true and applied in iteration.

In fact I found one solution, but not sure whether any side effect. Just add one line between line 144 and 145 in OSCCondition.cpp:

```
bool result = CheckCondition(storyBoard, sim_time, false);
result = result && evaluated_;    // added content
bool trig = CheckEdge(result, last_result_, edge_);
```

**Comment by eknabevcc** [comment] 2020-07-24 08:19
Hm, yes this is tricky. I still think that its correct behavior to miss the edge, since all evaluations evaluate to TRUE. The first evaluation will take place at time == 0.01 (since at 0.00 the act is not started yet, and hence the event conditions are not checked yet). In this very case it's tempting to "fix" the edge detection since we missed by just one single time step. But in the general case I think it would be wrong. E.g. if you want something to happen exactly at time==10 seconds, then the edge is useful. And if that condition is checked first time at 30 seconds it should not trig. But if you want to trig at any time above 10 seconds, then you could use edge=none.
But I really appreciate your idea and code proposal. It is perfectly aligned with how I wanted things previously. But after discussions within the OpenSCENARIO project (which led to the introduction of the "none" edge) I think "unfortunately" that esmini is behaving correctly.
I hope that you can agree, after all.

**Comment by wxtshr001** [comment] 2020-07-27 02:24
Well, maybe you are right, but I'll reserve my opinion. Missing the edge for rising/falling not only makes the scenario read&write more complicated, but also counter intuitive. Indeed the 'none' edge may solve the conflict, but, as far as I can see, not limited to the xosc example given by ASAM, and the xosc files I've ever seen, this kind of edge seldom appears. 

But on the other hand, if the edge are considered for rising/falling as I considered, then the none edge can cover all the rising/falling edges. For example: greaterThan+rising == greaterThan+none, lessThan+rising == lessThan+none..., etc. That makes the rising/falling meaningless.

By the way, I tested the scenario on VTD(openscenario 0.9.1 version). It is clearly that VTD doesn't miss edges. It would trigger no matter when the event condtion are checked.

**Comment by eknabevcc** [comment] 2020-07-28 11:30
I don't give up that easy! :) I don’t expect changing your mind, but please spend a few minutes reading the following message before closing the issue. 

First, two comments why edge=none seldom appear. 

1. It was first introduced in 1.0 (to solve situations where the edge concept was limiting or not needed), so it should not be found in 0.9.1 files.
2. The 1.0 standard requires the conditionEdge to be specified, however esmini will apply edge=none as default if missing. So there might be esmini example scenarios omitting the conditionEdge all together, implicitly choosing edge=none.

Now, I will do a final attempt to describe my understanding of the current 1.0 way of edges. 

Consider the following scenario: A blue car is being overtaken by a faster red car which will cut in after passing. Assume we want the red car to change lanes (cut in) when the gap distance has reached a specific number, let’s say 10 meters. Specified in more detail:

- Blue car is going forward in right lane at constant speed
- Red car is going forward in left lane, at higher speed 
- When the distance between vehicles becomes greater than 10 meters, trig the lane change

There are three possible variants of this scenario, see pictures below.
![Scenario variants](http://drive.google.com/uc?export=view&id=1W04AHQruIT1cLiwvdoDHPSDf0hMJG6vt)
1. Initial distance is > 10 m and decreasing
2. Initial distance is < 10 m (but will become 10 m sooner or later)
3. Initial distance is > 10 m and increasing

The lane change should only happen in version 1 and 2, not in variant 3 since the distance is way above 10 meters and the cut-in situation is not at hand.

Now, assume we use the edge = none. Variant 1 will fail since the lane change will trig immediately, which is not desired. Also in variant 3 the lane change will trig immediately, which is not desired. Only if the initial distance is less than 10 meters, as in variant 2, the scenario will work as desired. 
Here is where edge can help. Assume we use edge = rising. If the initial distance is larger than 10 meters  (variant 1 and 3) the trig will be prevented by missing edge (no evaluation so far, edge is undefined). In variant 1 the distance will gradually decrease to 0 and then increase again as the red car passes the blue one. When distance becomes > 10 meters the condition is true and since we also have a rising edge (last evaluation was false) we have the desired trig. In variant 3 the edge will never happen, and hence it prevents an unwanted lane change to take place. 

BTW, I guess distance < 10 with edge = falling would basically give the same result as distance > 10 with edge = rising (except that it will include the exact case of distance == 10, which is unlikely anyway)

So to conclude my view on edges: I see edges as means of extra constraints on triggers, to solve more complicated conditions. In most cases I think edge = none is good enough, like: Trig as soon as the condition is fulfilled, regardless of history.

Anyway, this was a highly useful “discussion” for me, I had to review the concept and think about it another round. I also realize that the standard could describe it better - to make it clearer and avoid diverging interpretations which in the end would lead to different implementations and simulation results. Perhaps a few examples highlighting use cases of the conditionEdge would be good as well.

It may be that we end up in different opinions, or rather interpretations, of the edge concept. That is perfectly OK given the unclear description. For now I will keep esmini edge behavior as is, but I might change my mind later :) I think we can close the issue, but since you opened it I think you should have the opportunity to have the last word!

**Comment by wxtshr001** [comment] 2020-07-31 09:06
@eknabevcc Thanks for your detailed explaination! I rethink it for some days, and I have to admit that it would be more trouble if edges not miss in the first time checked. So, the ASAM userguide may not so accurate about this point.

Also I checked the OpenScenario 0.9 user manual, the rising in older version says 

> the action will start when the Condition becomes true

That makes the trigger start as soon as the conditons are true, and that's the reason why it choose to start the event in the scenario I set initially.

So, in order to start an event in an act with SimulationTimeCondition, it is recommended that edges set to none because it increases monotonously.

Currently the simulation softwares like VTD/carmaker didn't release their newer edition which support OpenScenario 1.0 standard. I'll have a try when we got the release.

But, although ASAM provides the migration xslt file for conversion from 0.9 to 1.0, some problem would still exists as this we discussed. That's troublesome.

And thanks again for your answer! That's really helpful!

**Comment by eknabevcc** [comment] 2020-08-03 06:25
I agree with you that the information in previous (0.9.1) and current (1.0) documentation is not perfectly clear on edges. I wouldn't say it's wrong, but rather incomplete or not detailed enough (e.g. not clarifying WHEN an condition should be evaluated first time, which affect the edge I would say). 
I think that before the introduction of edge=none in 1.0 it made sense with a more relaxed interpretation of edges. So it could be that (hopefully only a few) 0.9.1 scenarios might need manual adjustment after automatic conversion (with xslt) to 1.0 in order to run as expected.
Anyway, it would be very interesting to hear the result from VTD/Carmaker runs with 1.0, when supported. You're highly welcome to share the result!
Meanwhile I will close this issue for now. But I'm sure we will come back to this topic. Since I'm still not 100% percent sure and OpenSCENARIO 1.1 might clarify edges in a way requiring esmini to adapt. 
Thanks a lot for your input and patience in this long discussion!

**Closed by eknabevcc** 2020-08-03 06:25 UTC
