### ISSUE TITLE
Help with the 'hello world example'

### ISSUE THREAD

**Issue by Kim-Y19** [esmini/esmini#77] opened 2021-02-18 14:08 UTC
Hi,
Anyone every had trouble before when running 'main.cpp'?
I got the following error:
main.cpp:(.text+0x2c): undefined reference to `SE_Init'
main.cpp:(.text+0x41): undefined reference to `SE_Step'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'main' failed
make: *** [main] Error 1

It doesn't help after i adjusted the 'SE_Init("../resources/xosc/cut-in.xosc", 0, 1, 0, 0);' to current folder or add -lpthread when compiling.
Thanks!!

**Comment by eknabevcc** [comment] 2021-02-18 18:25
Hi. that was an interesting issue. Thanks for reporting.
First, did you follow the initial steps in the [beginning of the HelloWorld guide](https://github.com/esmini/esmini/tree/master/Hello-World_coding-example#steps-to-build-the-hello-world-esmini-player-application)?
For example the cmake procedure, and then setting the environment variable LD_LIBRARY_PATH, like this:
`export LD_LIBRARY_PATH=.`
If you have issue with cmake you could try manual build command, from within folder "Hello-World_coding-example" something like:
`gcc main.cpp -I../EnvironmentSimulator/Libraries/esminiLib -L. -lesminiLib`
Also make sure that you have a copy of the libesminiLib.so in the "Hello-World_coding-example" folder.
Please try this and report back how it goes. We shall solve it!
By the way, if it does not work, what OS are you on? I guess Linux?

**Comment by Kim-Y19** [comment] 2021-02-19 09:42
Thanks a lot for your quick and detailed answer!! I appreciate it a lot!
I still have the same error.
It's Linux, and the cmake function is okay, the build folder is created. The libesminiLib.so is also under the example folder.
If i run the emmini-player.py, it's working normally. But the problem is to run the main.cpp. 
I tried with the export LD_LIBRARY_PATH=. I'm clear with how to use it. So i tried to run the exact same code under example folder and also tried to add the real path to example folder to it after '='. Also tried these for the build folder.

Thanks a lot for your time in helping me with an esmini starting question.

**Comment by eknabevcc** [comment] 2021-02-19 12:48
I see, it was a stubborn issue. Let's "rewind the tape" and take careful steps from beginning - just to find out whether it's something in your Linux-environment or not. Could you put yourself in the esmini root folder AND make sure there is libesminiLib.so file in the "Hello-World_coding-example" folder. Then perform the following steps exactly:
```
cd Hello-World_coding-example
rm -rf build
mkdir build
cd build
cmake ..
cmake --build . --config Release --target install
cd ..
export LD_LIBRARY_PATH=.
./esmini-player
```
I'm very curious about the result, does it work?
If this doesn't work: What Linux distribution do you have (Ubuntu, Leap, ...) and version e.g. 18.04?
Also next step would be to recompile the libesminiLib.so. By the way did you build that yourself, or is it from a release zip-package?
But let's start with you performing the steps above, and then we decide next step.
Thanks for patience.

**Comment by eknabevcc** [comment] 2021-02-23 15:36
By the way, I just realized one thing. I forgot to ask you if you have installed dependencies, like described here: https://github.com/esmini/esmini/blob/master/docs/BuildInstructions.md#additional-platform-dependencies

Anyway, the command should be:

`sudo apt install build-essential git pkg-config libgl1-mesa-dev libpthread-stubs0-dev libjpeg-dev libxml2-dev libpng-dev libtiff5-dev libgdal-dev libpoppler-dev libdcmtk-dev libgstreamer1.0-dev libgtk2.0-dev libcairo2-dev libpoppler-glib-dev libxrandr-dev libxinerama-dev curl cmake`

It's a long shot, but I ask anyway to rule out that potential root cause .

**Comment by Kim-Y19** [comment] 2021-02-25 13:32
Thanks a loooooot!!!! It works! Magically, and of course logically!!!
I think i understand it better now. Previously I thought I need to run the main.cpp directly and now I understand that actually the 'compiling programm' is here 'cmake ..
cmake --build . --config Release --target install'. A file 'esmini-player' will be created and then could run it. Please correct me if I don't understand it correct:)
I may have a few questions:
1. how was the main.cpp used in the program? I only see it calls some functions from esminiLib.hpp. I realize the program runs the main.cpp content and not the esmini-player content, even though to run it, the code is './esmini-player'
2. If we add driver model then the scenario is changed, could we save the data into xosc file and replay and save the video?
I want to say many thanks to you! Sorry for my late reply. but now i have more confidence to run and explore esmini more:)

**Comment by eknabevcc** [comment] 2021-02-25 13:59
Great news! You got it perfectly correct: The cmake --build command compiles the main.cpp code, links with the esmini library and spits out the esmini-player executable. (this could also be done within an IDE, for example Visual Studio, but cmake is easy to explain because it's the same on all platforms. Behind the curtains it will identify available compiler and create the build scrips accordingly).
1. The main.cpp defines what scenario to load, and then just steps the scenario. It should be same or similar to the [first example](https://github.com/esmini/esmini/tree/master/Hello-World_coding-example#hello-world---load-and-play-a-scenario).
2. The idea is that you copy-paste code from the other examples, e.g. [driver-model](https://github.com/esmini/esmini/tree/master/Hello-World_coding-example#driver-model). It's a bit more complex, but should work. Make sure you download the special scenario-file [test-driver.xosc](https://www.dropbox.com/s/h9uqj2la4sk2t2o/test-driver.xosc?dl=1), which is referred to by that example.

If you re-compile the modified main.cpp you should be able to re-run the esmini-player, now with the driver-model scenario and with your application code (main.cpp). 
Please try and feed back how it goes!

**Comment by eknabevcc** [comment] 2021-02-25 14:54
By the way, regarding video: Unfortunately there is no easy way to record a videos file from esmini.
You can easily save single screenshots with key 'c', but no video.
However, there's maybe an interesting alternative: You can record a scenario-run into a binary .dat file which can be re-played.

Try this, from esmini root folder:
`.\bin\esmini --window 60 60 800 400 --fixed_timestep 0.02 --osc .\resources\xosc\cut-in.xosc --record sim.dat`

(of course, you can replace --window 60 60 800 400 with --headless for a much quicker run, especially if you plan to view it in replayer afterwards, or if you're not interested in viewing the scenario)

You can then view the file in replayer:
`.\bin\replayer.exe --window 60 60 800 400 --res_path .\resources --file .\sim.dat`
Also try the key-shortcut commands to pause (space) and step the scenario forward and backwards (left/right arrow) (see complete list of commands here: [replayer/readme.txt](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Applications/replayer/readme.txt))

**Comment by Kim-Y19** [comment] 2021-02-25 22:19
Hi!
Thanks for your helpful and super quick response as you always do!!!
The solution you provided for recording a scenario and replay the scenario works perfectly! May i ask more details:

1. running '.\bin\esmini --window 60 60 800 400 --fixed_timestep 0.02 --osc .\resources\xosc\cut-in.xosc --record sim.dat', we don't need to compiling program (for main.cpp), as the function here is to run 'esmini' (within bin folder) to load and record the scenario 'cut-in.xosc' to 'sim.dat'. But if we have more codes in main.cpp then need to do 'cmake --build . --config Release --target install'. Do i understand correct?
2. In the codes for replay: why do we need to specify the resource path? what information is taken there? I understand it's needed to specify which file, replayer function and other information (window and time etc), but why resource path?
P.S. '.\bin\replayer.exe' doesn' work for me, but '.\bin\replayer' (removes exe) works:)

Now i'm trying two things: one is to follow the first example and include the driver model and the other is search how to combine two dat files together, so i could compare the original scenario and the scenario after adding the driver model. If i have any progress, you will be the first to know! thanks:)

**Comment by eknabevcc** [comment] 2021-02-26 09:20
Yes, you understand correct again. 
1. If you want to use you own main.cpp, then just adjust the SE_Init call so that the record flag = true. E.g:
`SE_Init(filename, 0, 1, 0, 1);`
The arguments are a bit cryptic, but you can find some info [here in the header-file](https://github.com/esmini/esmini/blob/f69155f10d2e24e59f0ff66716854888c02935f8/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L133).
It will create a .dat file with the same filename as the scenario, e.g. cut-in.dat, in the same folder where you run your esmini-player app from.

2. Ah, sorry. Of course, you're on a Linux system. Then you should not have .exe. You're totally right. 
Then regarding res_path: The dat file does not include actual road data and 3D models of road and vehicles. It just includes base filename for OpenDRIVE road description (.odr) and scenegraph model (.osgb). The OpenDRIVE is used to optionally plot road data (shortcut key 'o') and generate 3D model if the osgb is not provided. 
So to put it simple, I recommend to set --res_path to the esmini/resources folder or any folder containing the "xodr" and "models" sub-folders with needed content.

Interesting use case, comparing different runs. Combining .dat-files I've not thought about - interesting idea 👍

Maybe the plot-script can be of help as well. See example here: [run/replayer/run_and_plot_cut-in_speed.bat](https://github.com/esmini/esmini/blob/master/run/replayer/run_and_plot_cut-in_speed.bat)

**Comment by eknabevcc** [comment] 2021-03-01 14:29
By the way: We just released [v2.4.1](https://github.com/esmini/esmini/releases/tag/v2.4.1), adding some options that might be useful for driver modeling.

For example, a new function, [SE_SetLockOnLane](https://github.com/esmini/esmini/blob/4edd54e399453c59ed6c82d6644d9fc1a6cf3bf2/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L354), which will enforce lookahead in original lane - even when the vehicle has drifted sideways into a different lane, for example due to long look-ahead distance in a curve.

![image](https://user-images.githubusercontent.com/29146839/109510884-ce568780-7aa2-11eb-8302-ecb76a4846a0.png)

**Comment by Kim-Y19** [comment] 2021-03-02 13:46
Thank you! I have new questions:

1. how to save data so we could do post analysis? Now the output is from the scenario engine and we could visualize it. Is it possible to save it as a new xosc file? So a new scenario is created and saved. I'm also trying to save it as a JSon file so could make some plots of the dynamics:)

2. Whether is difficult or possible to include available driver model (or other model not in c++ format) in to the esmini simulation? I understand it's possible to add the scenario engine into python codes, but if we have a model in python (for example a driver model), is it possible to 'directly' use it?

Thanks again!

**Comment by eknabevcc** [comment] 2021-03-02 14:00
1. **Post analysis**. If you just want to review/replay the scenario I think the .dat/replayer method can serve. For post-analysis I propose to use
dat2csv:
`.\bin\dat2csv.exe .\sim.dat`
Then you can print the resulting sim.csv:
`cat sim.csv` from PowerShell (if you're in cmd use `type sim.csv`)
You can open the .csv in Excel as well. And you can plot stuff from it with esmini/scripts/plot_csv, e.g:
`.\scripts\plot_csv.py .\sim.csv --param speed`
There are two examples in run/esmini/replayer.
You'll need Python with matplotlib installed for the plot_csv script.

2. I don't have a simple answer. One approach would be to do similar to the [Driver Model](https://github.com/esmini/esmini/tree/master/Hello-World_coding-example#driver-model) example. But using a Python binding, like briefly outlined at [end of the Hello World page](https://github.com/esmini/esmini/tree/master/Hello-World_coding-example#python-binding). It the driver is independent (not needing information from esmini), then an idea could be to just report state to esmini via UDP. I could explain a bit more if you think that could be applicable to your use case.

**Comment by Kim-Y19** [comment] 2021-03-02 14:47
Thanks!! 
1. Yes, now i learnt how to save data to csv and successfully used your codes to do some plotting!
But I'm thinking if we could save the new scenario into also xosc file, then this 'new scenario' could also be loaded in the esmini and then apply new modifications (vehicle functions etc) and then maybe do some post analysis. It could be one way of generating many scenarios based on some example one.
2. If i understand correct:) If we need to have some input from esmini to the model in python, then it seems the only way is to include esmini in python and load its library in python. That is what i understand from the example below the hello world:) 
I was thinking what is the easier way (pros and cons) if we have scenario engine in esmini and driver model in python. One is to convert information from esmini to python readable function and the other way is to 'create driver model' from the concept of the driver model in python and add it as one external controller in esmini.

This is my current understanding and i really want to thank you again! From your answers and the hello world example I really learnt a lot. Now i know how to load scenario and run the scenario engine, how to add sensor and possible add some vehicle function (like braking) and how to update scenario, how to record and replay scenario and how to do convert data to csv and further do post analysis. Thousands of thanks! Super sure without your help I couldn't come to this stage now:)

May I ask what would be your suggestion if i want to continue exploring it? I have a use case which i want to do, but not sure if there any other 'handbook' thing i could look at when stuck with certain function:)

**Comment by eknabevcc** [comment] 2021-03-02 15:12
I think you are in the frontier of esmini use cases now :) So there's not really hand books on this stage...

Actually your last thinking, creating a driver model as a controller, could be a way forward. Either putting all driver model logics within the controller - or having the controller communicating with an external driver model via UDP for example.

The [ControllerFollowGhost](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Modules/Controllers/ControllerFollowGhost.cpp) and [ControllerInteractive](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Modules/Controllers/ControllerInteractive.cpp) are two examples that might give some ideas. But as said - there is no super-smooth way what I can see. I can just encourage you to experiment!

Regarding saving a new scenario. Saving (external) entity's motion as trajectory would be a pretty straight forward solution, but then it's hard to manipulate. And reverse-engineering parametric actions from the motion of a driver model would be very interesting indeed - but tricky. I have no good input to this, although I like the ideas.

**Comment by tmIdiada** [comment] 2021-03-02 15:38
Hi,
for the reversed way from trajectories back to clean / good readable OpenSCENARIO files I think you can only use deep learning methods.
But, handling of those things is very complicated, you would need one CNN per type of event and one CNN per type of trigger, Output of the single CNNs could be always a percentage rate, that really this event or trigger is satisfied by the trajectories and the other output would be always the parameters of the single event or trigger. The Input for the CNNs would be always the trajectories from esmini simulation.

**Comment by eknabevcc** [comment] 2021-03-03 05:58
Now we're pushing the frontier even more :)
I'm lost when it comes to deep learning and CNN's, but actually I now realize (thanks @tmIdiada) that using esmini to produce trajectories for the training part of machine learning could be a really efficient and cool thing. Since we have the blueprint (original OpenSCENARIO file).

**Comment by eknabevcc** [comment] 2021-03-26 07:41
I close this issue now since there is no immediate action planned. Fortunately it will still be available for re-visiting. For any future attack on the deep-learning topic we can open a new thread. 👍
And please just re-open if there are more related questions.

**Closed by eknabevcc** 2021-03-26 07:41 UTC

**Comment by Kim-Y19** [comment] 2021-03-26 08:07
Thank you very much!!!!

**Comment by eknabevcc** [comment] 2021-12-09 15:19
> 1. **Post analysis**. If you just want to review/replay the scenario I think the .dat/replayer method can serve. For post-analysis I propose to use
>    dat2csv:
>    `.\bin\dat2csv.exe .\sim.dat`
>    Then you can print the resulting sim.csv:
>    `cat sim.csv` from PowerShell (if you're in cmd use `type sim.csv`)
>    You can open the .csv in Excel as well. And you can plot stuff from it with esmini/scripts/plot_csv, e.g:
>    `.\scripts\plot_csv.py .\sim.csv --param speed`
>    There are two examples in run/esmini/replayer.
>    You'll need Python with matplotlib installed for the plot_csv script.
> 2. I don't have a simple answer. One approach would be to do similar to the [Driver Model](https://github.com/esmini/esmini/tree/master/Hello-World_coding-example#driver-model) example. But using a Python binding, like briefly outlined at [end of the Hello World page](https://github.com/esmini/esmini/tree/master/Hello-World_coding-example#python-binding). IF the driver is independent (not needing information from esmini), then an idea could be to just report state to esmini via UDP. I could explain a bit more if you think that could be applicable to your use case.

Update for v2.18.2:
plot_dat.py replaces the two-step sequence with dat2csv and plot_csv.py.

So if you just want to plot the data, run e.g:
`./scripts/plot_dat.py sim.dat --param speed`

And there's a Python version of the dat2csv: scripts/dat2csv.py
