### ISSUE TITLE
Make vehicles respawn at open road entry points to create endless scenarios

### ISSUE THREAD

**Issue by johschmitz** [esmini/esmini#108] opened 2021-04-30 15:01 UTC
Could you add an option to esmini that allows vehicles to respawn at open road ends in order to create endless scenarios? It seems to me that this is not possible right now or maybe I am missing something? Like highway traffic scenarios where all vehicles disappear at the end of the highway section and are respawned at the beginning?
Of course this is also interesting for pedestrians.
If you do so it is important to add some logic that avoids multiple vehicles respawning on the same entrance point simultaneously (overlapping). For that you might need some kind of queue of vehicles waiting for the next open respawn point.

Edit: This should work in a similar way as the new odrviewer version does it.

**Comment by eknabevcc** [comment] 2021-05-02 06:37
First, there is an OpenSCENARIO Condition that can be utilized for this; https://www.asam.net/static_downloads/modelDocumentation/content/EndOfRoadCondition.html
This can be combined with a [TeleportAction](https://www.asam.net/static_downloads/modelDocumentation/content/TeleportAction.html) to a specific road position.
Actually one of the esmini example scenarios, [resources/xosc/lane_change_simple.xosc](https://github.com/esmini/esmini/blob/master/resources/xosc/lane_change_simple.xosc) does somethin similar. Each time the car reach end of the road it will be teleported back to a start position. (But only for three times, since maximumExecutionCount="3" in this case).

I realize that this is maybe a bit cumbersome to set up manually, but in a use case where you generate the road network from script I think this combination of condition and action can be utilized to achieve what you want and similar things.

Then, your idea has some similarities to the concept of [TrafficSwarmAction](https://www.asam.net/index.php?eID=dumpFile&t=f&f=4092&token=d3b6a55e911b22179e3c0895fe2caae8f5492467#_maneuvergroups_maneuvers_events_and_actions), where vehicles are spawned and deleted at the edge of a elliptic area surrounding a central reference vehicle. That action is unfortunately not implemented yet. However it is in our backlog. Anyway, that action will have some capabilities like watching out for other road users, e.g. not spawning at at spot already occupied. Whenever that action is implemented we might be able to re-use features for similar stuff. 
Until then, there is no plan to implement something like this. 

But as usual, user are welcome to propose pull requests of features that they have implemented for their own use cases.

**Comment by johschmitz** [comment] 2021-05-02 07:44
I see that you really want to evolve your feature set around the
OpenSCENARIO standard and avoid proprietary extensions, I find that very
reasonable.

The teleport approach sounds promising, I need to check if one can combine
it with multiple spawn points and a random distribution.
However I believe avoiding multiple vehicles spawning into each other will
become complicated.
I wonder if it wouldn't be better to extend the standard with some endless
random simulation features including some recommendations for the
implementation..

**Comment by eknabevcc** [comment] 2021-05-02 09:01
Yes, esmini is focused on executing OpenSCENARIO descriptions. But there is some special features as well to support various use cases. It's a balance of effort and value. Sometimes incoming ideas are really low-hanging fruits why we sometimes choose to implement. 

I like your ideas, and these kind of features might become increasingly needed as AD evolves. E.g. exploratory testing and training of automation driving functions. It's possible that esmini will expand in this direction also. 

I think that the emerging OpenSCENARIO 2.0 better supports these kinds of use cases. While OpenSCENARIO 1.0 focus more on concrete scenarios typically for verification and regression testing. (But that's just my own reflections). 

That said, OpenSCENARIO 1.X actually has:
1. a few features for endless, random/ambient traffic. See [3.8. Traffic simulation](https://www.asam.net/index.php?eID=dumpFile&t=f&f=4092&token=d3b6a55e911b22179e3c0895fe2caae8f5492467#_traffic_simulation). Swarm being one of the examples.
2. from 1.1 supporting parameter distributions. See summary [here](https://www.asam.net/index.php?eID=dumpFile&t=f&f=4092&token=d3b6a55e911b22179e3c0895fe2caae8f5492467#_what_has_changed).

However none of these supported in esmini yet. (though parameter distribution can be achieved using the [scenariogeneration](https://github.com/pyoscx/scenariogeneration) framework with esmini or any other simulator supporting OpenSCENARIO 1.X). 

I also agree that the standard could include implementation ideas/recommendations for some features. 

By the way, if you have a specific idea for OpenSCENARIO 1.X, please let me/us know and we can potentially bring it to the table for consideration.

**Comment by johschmitz** [comment] 2021-05-02 10:14
Hm, for now I was actually imagining something rather simple, a low-hanging fruit as you say. At least I imagine it to be one.

It would go like this:
I would start esmini with one of:

    esmini --osc scenario.xosc --endless
    esmini --osc scenario.xosc --endless-simulation
    esmini --osc scenario.xosc --infinite
    esmini --osc scenario.xosc --continuous
    esmini --osc scenario.xosc --continous-simulation
    esmini --osc scenario.xosc --auto-respawn

And then esmini would just behave like odrviewer and all vehicles could keep on driving forever until I hit ESCAPE.
Since the code and idea for that exists in odrviewer I imagine this would be quite easy to implement for you?

**Comment by johschmitz** [comment] 2021-05-02 10:20
If this idea works well then later I would like such a "simple" endless simulation option to become part of the standard. I just believe for someone who wants to test his driving function it would make his life so much easier to have such a simple "endless/continuous simulation" switch to perform some initial and/or interactive testing. After all random sampling has been and will always be one useful engineering tool. If we make it dead simple I hope people will start using it and discover things they haven't thought about when manually modeling scenarios.

**Comment by eknabevcc** [comment] 2021-05-17 04:18
First regarding endless simulation. Actually in esmini endless simulation is the default, as long as the OpenSCENARIO file does not include a stop trigger. 

Then, regarding the feature of endless spawned stochastic traffic: I think the TrafficSwarmAction will bring exactly that. It also has this cool feature with parametric elliptic area to limit the traffic in case of large road networks - to avoid performance issues and still provide rich traffic around one or a few key/ego vehicles.
Instead of trying to implement a quick and dirty solution we will spend efforts on the Swarm thing. It's in the backlog. So it's a matter of prioritization when it can be done, from our side. 

I close this now. Please re-open for further questions/discussion.

**Closed by eknabevcc** 2021-05-17 04:18 UTC
