### ISSUE TITLE
(external / merged) csv logger and default esmini logging should be aligned (one day)

### ISSUE THREAD

**Issue by tmIdiada** [esmini/esmini#137] opened 2021-07-27 13:19 UTC
Hi,

I found the following issue, I'm not really interested in it, I wanted only to document it:

in the detailed csv logging the timestep 0 is missing, but instead of this the detailed csv file contains the last time step, which is not logged by default esmini logger in the dat-file.

Kind regards,

Thaddäus

**Comment by eknabevcc** [comment] 2021-07-29 07:57
Thanks for reporting this issue of the csv-logger missing first entry, wasn't aware of it. 
But I can't reproduce last entry missing in dat-file. I get the same last timestamp in both (detailed csv and csv converted from dat).

Anyway, the missing first entry in csv-logger should be fixed now by commit cf9bbeaa9a80fcf7d51ff90dfcc1654f66131fba. And it will be part of next release. (since it's not urgent, we'll not make an immediate release for this fix).

Please test when possible and let us know how it works. First timestamps should be 0 in both files and they should have same last timestamp.

**Comment by eknabevcc** [comment] 2021-08-06 11:56
BTW, the fix has now been released in [v2.12.4](https://github.com/esmini/esmini/releases/tag/v2.12.4).

**Comment by tmIdiada** [comment] 2021-09-11 10:40
Hi sorry for that long time and still I have not really the time for such tests. But yes I'm still aware of it, that I have here something to do. I try to test it soon.

**Comment by tmIdiada** [comment] 2021-09-14 12:34
It works now

**Closed** 2021-09-14 12:34 UTC

**Comment by eknabevcc** [comment] 2021-09-14 13:03
Thanks or feedback @tmIdiada - good news 👍
