### ISSUE TITLE
esmini calls GPU

### ISSUE THREAD

**Issue by qqkkwan** [esmini/esmini#236] opened 2022-02-15 06:07 UTC
Hi,
   on ubuntu 18.04 server with desktop，when i run esmini，the binary does not use GPU and the window runs slowly(my Graphics card and driver are ok and i tested). What could be the problem？

**Comment by eknabevcc** [comment] 2022-02-15 10:53
Hard to say. esmini should make use of graphics hardware by default. But the system might fall back to software rendering for some reason. It would be interesting for us to understand.
1. Can you share the esmini log file (log.txt)? 
2. How do you start esmini: Is it from command line? What arguments?

**Comment by qqkkwan** [comment] 2022-02-15 12:23
I start esmini use command line : ./bin/esmini --window 60 60 800 400 --osc ./resources/xosc/cut-in.xosc,
[log.txt](https://github.com/esmini/esmini/files/8068996/log.txt)

**Comment by eknabevcc** [comment] 2022-02-15 14:01
For the investigation, could you please try the following:

`./bin/esmini --window 60 60 800 400 --osc ./resources/xosc/cut-in.xosc --aa_mode 0`
It will enforce basic mode without anti-alias filtering. 

And by the way, I see that the esmini version is fairly old. Also for the investigation, could you download and try with the latest version of esmini, e.g. [v2.20.6](https://github.com/esmini/esmini/releases/tag/v2.20.6).

Let us know if more recent version works as is. And also if the "--aa_mode 0" makes a difference.

**Comment by qqkkwan** [comment] 2022-02-16 10:38
Hi,
   I did what you did, but the result hasn't changed. :(

**Comment by eknabevcc** [comment] 2022-02-16 11:27
Did you also run the latest version? (double checking because the one you had is quite old)

**Comment by qqkkwan** [comment] 2022-02-22 08:43
yes,i have run the latest version

**Comment by eknabevcc** [comment] 2022-02-22 15:05
Ok, then the hunt continues. First, could you try the following:

`./bin/esmini --window 60 60 800 400  --disable_off_screen --osc ./resources/xosc/cut-in.xosc`

It will disable one step reading back the rendered image from HW to RAM. Make sure you run a recent esmini, at least version >= 2.19.0.

If no change, we should check some config and settings. Can you run the two following commands and post the result?
```
lspci -vnn | grep VGA -A 12
glxinfo -B
```
glxinfo might require install mesa utils: `sudo apt install mesa-utils`

**Comment by qqkkwan** [comment] 2022-02-24 13:55
**lspci -vnn | grep VGA -A 12:**
00:02.0 VGA compatible controller [0300]: Cirrus Logic GD 5446 [1013:00b8] (prog-if 00 [VGA controller])
        Subsystem: Red Hat, Inc. QEMU Virtual Machine [1af4:1100]
        Flags: fast devsel
        Memory at fa000000 (32-bit, prefetchable) [size=32M]
        Memory at fe010000 (32-bit, non-prefetchable) [size=4K]
        Expansion ROM at 000c0000 [disabled] [size=128K]
        Kernel driver in use: cirrus
        Kernel modules: cirrusfb, cirrus

00:03.0 Multimedia audio controller [0401]: Intel Corporation 82801AA AC'97 Audio Controller [8086:2415] (rev 01)
        Subsystem: Red Hat, Inc. QEMU Virtual Machine [1af4:1100]
        Physical Slot: 3
        Flags: bus master, medium devsel, latency 0, IRQ 11

**glxinfo -B：**
name of display: localhost:19.0
display: localhost:19  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: VMware, Inc. (0xffffffff)
    Device: llvmpipe (LLVM 10.0.0, 256 bits) (0xffffffff)
    Version: 20.0.8
    Accelerated: no
    Video memory: 32167MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: llvmpipe (LLVM 10.0.0, 256 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 20.0.8
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.1 Mesa 20.0.8
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 20.0.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10

**Comment by eknabevcc** [comment] 2022-02-25 16:10
Thanks. This is outside my comfort zone, but it would be interesting to find out root cause and even more a solution.
It seems like esmini (using [OpenSceneGraph](http://www.openscenegraph.org/) for 3D rendering), for some reason, finds the [llvmpipe](https://docs.mesa3d.org/drivers/llvmpipe.html) software OpenGL graphics driver instead of the Cirrus Logic GD 5446 hardware driver. 

Do you run remotely? And other 3D apps works good while esmini "crawls"? I don't have much of a clue why. I too would have to "google and experiment", which is hard when I don't have same setup. 

One interesting test would be to run osgviewer (or some other OpenSceneGraph application) to see if it's related to OSG or specifically esmini way of using OSG.

BTW: Did you try the `--disable_off_screen` flag?

**Comment by qqkkwan** [comment] 2022-02-28 00:42
Hi,
    It occurred to me that I do run remotely， i use MobaXterm on windows，I don't know why it happens，the  window is not as same as the real one in the real machine. But when i run esmini on the real machine，it seems to be normal. Anyway thank you for your reply and help me find the problems.

**Comment by eknabevcc** [comment] 2022-02-28 06:04
Thanks for info. Unfortunately I also experience performance degradation when running esmini remotely over Internet. What I then sometimes do is to reduce size of the window, e.g: esmini --window 60 60 400 200 .... 
But yes, good that we found the explanation! 👍
Closing the ticket.

**Closed by eknabevcc** 2022-02-28 06:04 UTC
