### ISSUE TITLE
Build failed (v2.26.5) undefined reference to `pthread_yield'

### ISSUE THREAD

**Issue by ashahzad-v** [esmini/esmini#329] opened 2022-10-06 08:44 UTC
Hello! I am trying to use esmini on linux but the build keeps on failing. 
![image](https://user-images.githubusercontent.com/111045809/194265455-7f192a37-3659-456f-8643-598c6fa390fc.png)

I am following the instructions here:(https://esmini.github.io/#_esmini_embedded_controllers:~:text=Network%20Editor.-,2.3.%20Build%20esmini%20%2D%20quick%20guide,-Supported%20systems%3A%20Windows). I have installed the dependencies required for Linux but that is not helping. 

I also tried to use the built binaries as well but there I get told off due to access denied. 
<img width="598" alt="image" src="https://user-images.githubusercontent.com/111045809/194265373-b4fdaaba-79dc-4c96-bf41-dbdecdd95563.png">

**Comment by eknabevcc** [comment] 2022-10-06 10:34
Thanks for reporting! 
Root cause is pthread_yield has been deprecated in recent glibc. I guess you're running on recent Ubuntu, e.g. 22.04.
We're working on it.
If you need a temporary solution: grab [this osg lib package](https://esmini.asuscomm.com/AICLOUD766065121/libs/osg_linux_glibc_2_35_gcc_11_2.7z) and replace existing subfolder external/OpenSceneGraph/linux. For example, run following from esmini root:

```
cd externals
mv OpenSceneGraph OpenSceneGraph-save
7z x ~/Downloads/osg_linux_glibc_2_35_gcc_11_2.7z -oOpenSceneGraph
```
If 7zip is missing:
`sudo apt install p7zip-full`

**Comment by eknabevcc** [comment] 2022-10-07 16:32
OSG library (with sched_yield patch) has now been rebuilt with gcc 7.5.0 and glibc 2.31 - which seems to be working fine for at least Ubuntu 18.04, 20.04 and 22.04. This is now the default lib for future builds.

Either get the lib from here: [osg_linux_glibc_2_31_gcc_7_5_0.7z](https://esmini.asuscomm.com/AICLOUD766065121/libs/osg_linux_glibc_2_31_gcc_7_5_0.7z)
or, since this lib is now default, delete externals/OpenSceneGraph folder and re-run `cmake ..` and build command (as explained [here](https://esmini.github.io/#_build_esmini_quick_guide)).

**Comment by eknabevcc** [comment] 2022-10-10 06:24
Regarding the "Permission denied": I suspect somehow the file mode bits has been changed. 
It should look like: 
![image](https://user-images.githubusercontent.com/29146839/194808249-76247736-3644-4371-8232-05a16e318743.png)
But maybe you have: `-rw-r--r--` instead of `-rwxr-xr-x`?
Anyway, try to restore with command: `chmod +x esmini`

**Comment by eknabevcc** [comment] 2022-10-14 15:07
I think we can close this now. Let us know if issue remains or pops up again.

**Closed by eknabevcc** 2022-10-14 15:07 UTC

**Comment by ashahzad-v** [comment] 2022-10-17 09:16
> Thanks for reporting! Root cause is pthread_yield has been deprecated in recent glibc. I guess you're running on recent Ubuntu, e.g. 22.04. We're working on it. If you need a temporary solution: grab [this osg lib package](https://esmini.asuscomm.com/AICLOUD766065121/libs/osg_linux_glibc_2_35_gcc_11_2.7z) and replace existing subfolder external/OpenSceneGraph/linux. For example, run following from esmini root:
> 
> ```
> cd externals
> mv OpenSceneGraph OpenSceneGraph-save
> 7z x ~/Downloads/osg_linux_glibc_2_35_gcc_11_2.7z -oOpenSceneGraph
> ```
> 
> If 7zip is missing: `sudo apt install p7zip-full`

Thanks a lot. Replacing the osg package fixed the issue.
