### ISSUE TITLE
Using UserDefinedValueCondition leads to seg fault

### ISSUE THREAD

**Issue by arauschert** [esmini/esmini#165] opened 2021-10-01 09:34 UTC
Whenever having a UserDefinedValueCondition within a scenario, esmini is not able anymore to execute the scenario. There is a seg fault upon scenario execution:

TrigByValue UserDefinedValueCondition not implemented
Segmentation fault (core dumped)

**Comment by arauschert** [comment] 2021-10-01 10:13
From looking at the code it seems like this will happen whenever a non-implemented condition is used. The condition is added to the condition group anyway although parseOSCCondition returns 0 (see ScenarioReader.cpp#L3123):

			OSCCondition *condition = parseOSCCondition(cNode);
			condition_group->condition_.push_back(condition);

By the way: is ScenarioReader::ParseConditionGroup() used at all or only ScenarioReader::parseTrigger()?

**Comment by eknabevcc** [comment] 2021-10-01 11:51
Very good finding. esmini should not crash. The fix will put a WARNING to the console/log that it's not supported but still continue trying to run the scenario without that condition. 
And yes, we removed the obsolete ParseConditionGroup - thanks 👍

By the way, could you tell your use case for the UserDefinedValueCondition? Just as an example and perhaps motivation for us to add support for it.

**Comment by arauschert** [comment] 2021-10-01 11:59
Great, thanks  a lot!

The use-case for the UserDefinedvalueCondition would be the possibility to trigger actions in the scenario from outside the scenario. The environment simulation would only need a generic interface to set user defined values from outside and keep e.g. a map<string, string> of these values. This is sufficient for implementing the UserDefinedvalueCondition comparison (if the value doesn't exist, the condition is false). The triggers can then come from various external sources. One example could be from a test software, which either has a manual trigger in a GUI or an automated trigger in a test case.

**Comment by eknabevcc** [comment] 2021-10-04 05:23
Thanks for explanation! Yes, this sounds like useful and straight forward use cases. 👍

**Comment by eknabevcc** [comment] 2022-10-12 09:28
Sorry for late response. The use case is very useful. And we now realize that we have used Parameters for the same use case with esmini, since almost two years. 

**History**
Parameters can be monitored by conditions ([ParameterCondition](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.1.1_Model_Documentation/modelDocumentation/content/ParameterCondition.html)) and the parameter value can be changed by the scenario ([ParameterSetAction](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.1.1_Model_Documentation/modelDocumentation/content/ParameterSetAction.html)) enabling to control the parameters and hence triggers from within the scenario. So we figured, why not extend the use of parameters to make them readable and writable from an external process, e.g. vehicle simulator, as well?

The advantage with parameters is that they are typed, while [UserDefinedValueCondition](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.1.1_Model_Documentation/modelDocumentation/content/UserDefinedValueCondition.html) is not (just a generic string). I agree that since a user defined parameter is a contract between the user and simulator the type can be assumed to be known anyway, so that for example a double is extracted from the string using `strtod()` or similar. 

An API interface was needed regardless, so we decided to add an API allowing to read and set parameter values. I admit that this is/was a bit stretching the standard since it says nothing about external manipulation of parameter values. But it was simply a too valuable solution to be ignored. That's when the [SE_GetParameter* and SE_SetParameter*](https://github.com/esmini/esmini/blob/9bda5438f1745c302ea84882e8864477fcd2f683/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L443) functions were created. 

To conclude, I think having this solution in place lowered the priority of implementing the UserDefinedValueCondition.

**Present status**
But all that said, OpenSCENARIO 1.2 introduces [variables](https://www.asam.net/index.php?eID=dumpFile&t=f&f=4908&token=ae9d9b44ab9257e817072a653b5d5e98ee0babf8#_variables) and [VariableAction](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.2.0_Model_Documentation/modelDocumentation/content/VariableAction.html) which is a great thing since 1. It brings the functionality we need for the use case, in an "legal" way and 2. We can keep parameters as intended, just a static placeholder for a constant value in the scenario file - similar to the preprocessor `#define` directive in the C/C++ language.

esmini does not yet support variables, but it's in the backlog (and probably quite simple to implement basically moving functionality from parameters).

I close the issue since it was about the UserDefinedValueCondition which esmini is not supporting, and no current plans to support.

**Closed by eknabevcc** 2022-10-12 09:28 UTC
