### ISSUE TITLE
Crash when SE_GetRoadInfoAtDistance method called for a vehicle created by SE_AddObject method 

### ISSUE THREAD

**Issue by Genco2** [esmini/esmini#263] opened 2022-03-30 11:15 UTC
Hello Everyone;
I am working to create a new vehicle(2 vehicles were already existing, new one is the 3rd one) at a given time. I am using SE_AddObject function with no problem.
When following code block executed ; 
`		
	
                    insertedID = SE_AddObject("insertedVehicle", 1, 0, 1);
			printf("ID : %d \n",insertedID);
			y = SE_ReportObjectPosXYH(insertedID, 0, vehicleState.x, vehicleState.y, vehicleState.h, 10.0);
			SE_GetObjectState(insertedID, &insertedObjectState);
			insertedVehicleHandle = SE_SimpleVehicleCreate(vehicleState.x, vehicleState.y, vehicleState.h, 4.0, 10.0);
                        ...
			SE_SimpleVehicleGetState(insertedVehicleHandle, &insertedVehicleState);

`

I obtain the new vehicle just where I wanted which is the same location as the vehicle with vehicleState struct and can reach insertedObjectState struct. However when I tried to call SE_GetRoadInfoAtDistance function to obtain steer angle for the newly added vehicle; 
`y = SE_GetRoadInfoAtDistance(2, 5 + 0.75f * insertedVehicleState.speed, &roadInfo, 0, true);
`
simulation crashes without a message. May first idea is maybe the vehicle created by the "SE_AddObject" method does not have "pos_.GetHRelativeDrivingDirection() " . Does anyone have any idea ? 
Thanks a lot.
Genco Cosgun

**Comment by eknabevcc** [comment] 2022-08-31 16:29
Thanks for this report, sorry for delayed response.

You sure found a bug. Root cause was a reference to a member in the not yet created visual model. The problem is that when adding a vehicle, the actual 3D model is not created until the SE_Step() method is called. And actually, even when created it was not done fully correct (bug).

This should be fixed by commit 084f57dd398fd230303656a9ac76a3936518b066. However, the commit only fixes:
1. Avoid referring to non existing 3D model
2. Create 3D model correct after AddEntity()

So you still need to run SE_Step() at least once to 1. have the model created and 2. update the sensor info. So i suggest you add a `SE_StepDT(0.0)` somewhere before SE_GetRoadInfoAtDistance(), or postpone that call to next frame.

**Comment by Genco2** [comment] 2022-09-11 07:41
Thanks a lot for the help, always happy to use Esmini :) Closing this issue.

**Closed** 2022-09-12 05:22 UTC
