### ISSUE TITLE
no wheel rotation with ExternalController

### ISSUE THREAD

**Issue by sterres** [esmini/esmini#163] opened 2021-09-30 09:50 UTC
Hi,

I just found out, that the wheels of the vehicle will not spin, if it is controlled via external controller. I'm using SE_ReportObjectPosXYH() / SE_ReportObjectPos().

For the SE_ReportObjectSpeed(), I can see in the source code, that the wheel angle is modified:
https://github.com/esmini/esmini/blob/bfaad98ea2996ad4faf145200e6b5c3b9ab5a068/EnvironmentSimulator/Libraries/esminiLib/esminiLib.cpp#L854-L876

I tried to combine the 2 functions, but if I put the reportSpeed after the reportPos, the position is frozen and wheels turn. The opposite order has no effect on the wheels but position is synced.

Can this be solved by adding the wheel_rot code from reportSpeed to reportPos? Or is more complicated due to the underlying controller logic.

Best regards
Simon

**Comment by eknabevcc** [comment] 2021-10-01 06:23
Thanks for pointing out this issue. Yes, It's a bug, overwriting wheelAngle and wheelRotation with 0.0 each time from esminiLib ReportObjectPos functions. 
It should be fixed with this commit: eaf474d90311c080048ee6c7298ceafcc92a06ca

Can you build esmini yourself? Anyway it will be part of next release, which is planned today or Monday.

Let us know when you have tested if it works better or not.

**Comment by sterres** [comment] 2021-10-01 07:02
I built the newest master branch but it seems to not to solve the issue.

I'm sending valid values for all parameters:
SE_ReportObjectPosXYH(ego_id, time, pos.x, pos.y, pos.h, pos.speed);

And then call 
SE_StepDT(communicationStepSize); 

Any idea what could be going wrong?

**Comment by sterres** [comment] 2021-10-01 07:11
Update: Problem seems to be with my build pipeline. The files in bin were not updated.
I'll fix that and report back when I tested it.

**Comment by sterres** [comment] 2021-10-01 07:39
I think there is some conflict with Windows WSL.

In my version.txt I got

ESMINI_GIT_REV="eaf474dF³r das Windows-Subsystem f³r Linux wurden keine Distributionen installiert.


Distributionen zur Installation finden Sie im Microsoft Store:


https://aka.ms/wslstore"

This is also taken in version.cpp and causes a build error.

Guess this is an issue on my side than a esmini bug. 

I can fix this by modifying version.cmake in line 33 to
set(VERSION "const char* ESMINI_GIT_REV=\"${GIT_REV}\";


Wheels are turning now :)

**Comment by eknabevcc** [comment] 2021-10-01 08:07
Oops, that git rev issue I've never seen. The idea with the GIT_DIFF check is to add a '+' if the code has been modified from the pure revision. 

Will keep this issue in mind and see if we can understand root cause and fix. Your temporary fix is fine, just that it will look like esmini version is exactly as the git committed revision. Which probably is not a big issue for you :)

Good news regarding wheels turning! Thanks for letting us know. I close this issue now.

**Closed by eknabevcc** 2021-10-01 08:07 UTC

**Comment by sterres** [comment] 2022-04-04 09:40
Hi, 
I have to reopen this - with the newest release (2.21.2) and also (quite many) releases before the rotation seems not to work anymore. It still works, when I compile your specific commit mentioned above.

Is there some additional requirements when syncing position externally that have to be considered now? 

Esmini info text shows a correct velocity of 50 km/h - so I think the info is there to calculate the wheel rotation speeds.

**Comment by eknabevcc** [comment] 2022-09-15 15:44
Thanks for reporting this issue. You're right.
We've now changed the default behavior so that wheels will roll and steer based on vehicle motion (commit c0d815cda69f74ce9e0e0153476e926bfd84feaf).

Of course, values can still be overridden by reporting for the external vehicle. 

Also see [release notes](https://github.com/esmini/esmini/blob/master/release_notes.md#2022-09-15-version-2264) for [v2.26.4](https://github.com/esmini/esmini/releases/tag/v2.26.4).
