### ISSUE TITLE
elevation wrong

### ISSUE THREAD

**Issue by csawp** [esmini/esmini#327] opened 2022-09-29 09:28 UTC
OSI cannot handle this xodr. The elevation chages in a line.
[ElevationChangeIn50MLine.zip](https://github.com/esmini/esmini/files/9673248/ElevationChangeIn50MLine.zip)
![image](https://user-images.githubusercontent.com/114643211/192995230-903fd8bd-a3e9-4577-836b-ab962f05d27b.png)
wrong shape

**Comment by csawp** [comment] 2022-10-06 06:27
![image](https://user-images.githubusercontent.com/114643211/194229296-3294fe34-8a86-4bf0-9749-9123dfe85512.png)
Basically OK, but there are a few small flaws. It's not important
But repeatedly load many memory leaks lane and LaneSection

Or, for example
![image](https://user-images.githubusercontent.com/114643211/194229843-2272bc08-ac57-4069-beee-7dde9807a6f8.png)

No release

**Comment by csawp** [comment] 2022-10-07 15:31
class lane and class LaneSection

![image](https://user-images.githubusercontent.com/114643211/194591780-5d91d23c-82cb-46f4-9567-8010756ec578.png)
![image](https://user-images.githubusercontent.com/114643211/194591925-91cacedb-e0aa-4e2f-b876-b7a599bbf6a3.png)
Thanks for fixing the bug, but there are some places that haven't been fixed

**Comment by eknabevcc** [comment] 2022-10-07 16:31
Thanks for testing - good finding that additional bug!

Committed fixes included in release [v2.26.6](https://github.com/esmini/esmini/releases/tag/v2.26.6).

Regarding memory leakage. I fixed the first one. We'll not have time to do more right now due to other prioritizations. But anyone that finds and can fix glitches are welcome to do a pull request. I like that approach since the cred (commit owner) goes to the finder 👍.

**Comment by csawp** [comment] 2022-10-19 02:26
Destructor releases memory completely
Road::~Road()
{
	for (size_t i = 0; i < geometry_.size(); i++)
	{
		delete(geometry_[i]);
	}
	geometry_.clear();
	for (size_t i = 0; i < elevation_profile_.size(); i++)
	{
		delete(elevation_profile_[i]);
	}
	elevation_profile_.clear();
	for (size_t i = 0; i < super_elevation_profile_.size(); i++)
	{
		delete(super_elevation_profile_[i]);
	}
	super_elevation_profile_.clear();
	for (size_t i = 0; i < super_elevation_shape_profile_.size(); i++)
	{
		delete(super_elevation_shape_profile_[i]);
	}
	super_elevation_shape_profile_.clear();
	for (size_t i = 0; i < link_.size(); i++)
	{
		delete(link_[i]);
	}
	link_.clear();
	for (size_t i = 0; i < lane_section_.size(); i++)
	{
		delete(lane_section_[i]);
	}
	lane_section_.clear();
	for (size_t i = 0; i < lane_offset_.size(); i++)
	{
		delete(lane_offset_[i]);
	}
	lane_offset_.clear();
	for (size_t i = 0; i < signal_.size(); i++)
	{
		delete(signal_[i]);
	}
	signal_.clear();
	for (size_t i = 0; i < object_.size(); i++)
	{
		delete(object_[i]);
	}
	object_.clear();
}
		~LaneSection()
		{
			for (size_t i = 0; i < lane_.size(); i++)
			{
				delete lane_[i];
			}
			lane_.clear();
		}
		~Lane()
		{
			for (size_t i = 0; i < link_.size(); i++)
			{
				delete link_[i];
			}
			link_.clear();

			for (size_t i = 0; i < lane_width_.size(); i++)
			{
				delete lane_width_[i];
			}
			lane_width_.clear();


			for (size_t i = 0; i < lane_height_.size(); i++)
			{
				delete lane_height_[i];
			}
			lane_height_.clear();

			for (size_t i = 0; i < lane_roadMark_.size(); i++)
			{
				delete lane_roadMark_[i];
			}
			lane_roadMark_.clear();

			delete lane_boundary_;
			lane_boundary_ = 0;
		}

**Comment by eknabevcc** [comment] 2022-10-19 10:35
Excellent, thanks for the code!

But instead of me committing it I really want to encourage you to file a pull request - so that the commit will be associated with your GitHub user.

Here's a guide how to do it: 
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

(you need write-access to the repo from which you do the pull request, that's why external esmini users need to do it from a fork that they own)

Of course, if you don't want to or don't have the time: Just let me know and I will copy the code and do the commit.

**Comment by eknabevcc** [comment] 2022-10-21 07:16
Thanks for the pull request (#336)!
Closing this issue now since the issue is solved within this issue and some memory leaks solved by your pull request.

**Closed by eknabevcc** 2022-10-21 07:16 UTC
