### ISSUE TITLE
ParamPoly3::EvaluateDS() returns wrong value on a specific geom?

### ISSUE THREAD

**Issue by brifsttar** [esmini/esmini#17] opened 2020-05-01 16:30 UTC
Hi,

I have an *.xodr which have a geometry that somehow makes ParamPoly3::EvaluateDS() go crazy. Since I can't share the whole *.xodr, here's the geometry line that causes issues:

```
<geometry s="0" x="-1096.3684428373817" y="-533.4096859078702" hdg="3.6849934514250173" length="10.836506271255859">
    <paramPoly3 pRange="normalized" aU="0" bU="12.024944062662236" cU="-9.0567143281122586" dU="2.1188575530043776" aV="0" bV="-1.7763568394002505e-15" cV="-15.827183832673695" dV="7.4526055111209653" />
</geometry>
```

The road along the geometry in RoadRunner looks like this.

![RoadRunner](https://i.imgur.com/HHwiPFB.png)

I used Position::MoveAlongS() to travel along this road (bottom lane, no offset, 1m step), and plotted the resulting X/Y coordinates

![Plot](https://i.imgur.com/Z8tSdGq.png)

Obviously, that's not what I expected. Both "straight" extremities are predecessor/successor, I kept them in this plot as reference. I looked at track coordinates (S, T) and they looked fine. Only X, Y and heading seemed wrong.

I tried to debug it myself, looking around ParamPoly3::EvaluateDS() to see what could be wrong, but my poor math skills failed me.

**Comment by brifsttar** [comment] 2020-05-02 13:32
I plotted more things, and I managed to reproduce the issue in RoadRunner if I remove those lines from the road declaration

```xml
<laneOffset s="0" a="8.0470581516279562" b="-0.0015518285952879777" c="1.3711908013277687" d="-1.5343170713315633" />
<laneOffset s="0.88146497931321333" a="8.0602540195476475" b="-1.1606418665715443" c="0.54585854125706335" d="-0.039166357212443305" />
<laneOffset s="7.525141535954571" a="12.957466728876136" b="0.90614781025203817" c="-0.45698342941205722" d="0.064498391536051553" />
```

So I guess somewhere in RoadManager the lane offset is forgotten? I'm heading back to debugging!

**Comment by brifsttar** [comment] 2020-05-02 15:21
More info on my fix in #18.

The heading returned by ParamPoly3::EvaluateDS() is causing the issues downstream. The XY coordinates look all right, but the heading is way off. Here is the returned heading, plotted for each meter of the road (angle in degree).

![Plot](https://i.imgur.com/8jlzAUy.png)

For reference, the raw geometry looks like this

![Plot](https://i.imgur.com/0wmvCqq.png)

I don't really understand the following line

https://github.com/esmini/esmini/blob/fb1c46612a598e011a927cfb67c7e8a606e37a4c/EnvironmentSimulator/RoadManager/RoadManager.cpp#L258

So I replaced it with a simple atan2 which I understand, and the resulting XY coordinates are much better

![Plot](https://i.imgur.com/Vjr29io.png)

PS: I know I should label my diagrams, sorry :-(

**Comment by eknabevcc** [comment] 2020-05-05 11:25
Excellent problem report! This input and your proposed solution was very helpful to find root cause and final fix, which should be part of master branch from commit https://github.com/esmini/esmini/commit/bdb50367026142791666278e769813247fec70b1 onward.
Thanks for sharing that ODR snippet. It really helped since it made use of the Normalize parameter range type which I have not tested before - and probably would not think of as the root cause.
I'll leave this open until we see all works as expected.

**Comment by eknabevcc** [comment] 2020-05-07 18:05
Did you have any chance to test it? When you have, please indicate whether it works better - but make sure to include the parameter scaling, that was added in the [bdb5036](https://github.com/esmini/esmini/commit/bdb50367026142791666278e769813247fec70b1) commit.

**Comment by brifsttar** [comment] 2020-05-08 08:09
I just did a quick virtual test drive through the road network that had this issue, and everything was working fine. I can't say whether it was better or not though.

**Comment by eknabevcc** [comment] 2020-05-10 18:00
Ok. Thanks for confirmation! And thanks again for identifying the problem. I close this now.

**Closed by eknabevcc** 2020-05-10 18:00 UTC
