### ISSUE TITLE
OdrViewer 

### ISSUE THREAD

**Issue by TKeutgens** [esmini/esmini#86] opened 2021-03-09 16:41 UTC
Using the ordviewer I get a similar issue as in https://github.com/esmini/esmini/issues/64

Is it possible to add the --samples statement as input to der odrviewer?

**Comment by eknabevcc** [comment] 2021-03-10 06:44
Not sure that it solves root cause of the problem, but:

The `--samples` argument is supported in odrviewer as well. Actually odrviewer application will ignore it but it's forwarded to the OSG viewer which will use it when setting up the graphics window.

So please try from esmini root folder, for example:
` ./bin/odrviewer --samples 0 --window 60 60 800 400 --odr ./resources/xodr/e6mini.xodr`

This should launch the odrviewer with no anti-aliasing at all, so you should be able to see some "jaggies" on contours. 

![image](https://user-images.githubusercontent.com/29146839/110587421-f5cce480-8173-11eb-8a90-4d39e8c34284.png)

![image](https://user-images.githubusercontent.com/29146839/110587507-12691c80-8174-11eb-9de9-813274e4f0c8.png)

Compared to `--samples 4`:

![image](https://user-images.githubusercontent.com/29146839/110587730-4e9c7d00-8174-11eb-8f04-b192ef16e2e4.png)

![image](https://user-images.githubusercontent.com/29146839/110587767-5c520280-8174-11eb-957f-710fabafaf52.png)

**Comment by TKeutgens** [comment] 2021-03-10 08:47
Thanks for the quick reply!

Unfortunately, the odrviewer does still crash when displaying the scene. Esmini on the other hand is able to display the scene properly.  

The output of the odrviwer is:
`
esmini GIT REV: 9006a76
esmini GIT TAG: v2.3.0
esmini GIT BRANCH: tags/v2.3.0^0
esmini BUILD VERSION: 2.3.0.build.1124
density: 1.00
global speed factor: 1.00
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 0 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[1]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[2]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[3]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[4]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[5]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[6]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[7]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[8]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[9]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[10]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[11]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[12]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[13]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[14]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[15]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[16]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[17]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[18]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[19]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[20]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[21]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[22]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[23]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[24]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[25]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[26]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[27]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[28]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[29]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[30]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[31]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[32]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[33]:
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 1 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Stencil_BIKE
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[1]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[2]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[3]: Stencil_Bicycle1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[4]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[5]: Stencil_MERGE
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[6]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[7]: Stencil_ArrowType1Short
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[8]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[9]: Stencil_AHEAD
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[10]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[11]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[12]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[13]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[14]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[15]:
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 4 lane -2. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 4 lane -2. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[1]: Stencil_STOP
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[2]: StopSign
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: StopSign
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]:
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 10 lane 2. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Assembly1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[1]: StripedRegion
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 12 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 13 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 1468 / roadmanager::Road::AddSignal(): Add signal[0]:
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 14 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 16 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 16 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Stencil_STOP
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[1]: Stencil_BUS
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[2]: Stencil_BUS
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[3]: Stencil_STOP
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[4]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[5]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[6]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[7]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[8]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[9]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[10]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[11]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[12]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[13]:
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 20 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 20 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[1]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[2]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[3]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[4]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[5]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[6]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[7]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[8]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[9]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[10]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[11]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[12]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[13]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[14]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[15]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[16]: Stencil_BUS
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[17]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[18]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[19]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[20]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[21]: Stencil_MERGE
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[22]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[23]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[24]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[25]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[26]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[27]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[28]: Stencil_AHEAD
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[29]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[30]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[1]: Stencil_STOP
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[2]: Stencil_Bicycle2
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[3]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[4]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[5]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[6]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[7]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[8]: Stencil_Bicycle2
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[9]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[10]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[11]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[12]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[13]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[14]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[15]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[16]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[17]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[18]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[19]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[20]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[21]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[22]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[23]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[24]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[25]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[26]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[27]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[28]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[29]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[30]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[31]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[32]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[33]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[34]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[35]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[36]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[37]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Stencil_Bicycle2
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 27 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 27 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 1468 / roadmanager::Road::AddSignal(): Add signal[0]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[1]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[2]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[3]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[4]: Stencil_Bicycle2
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 31 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 31 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Stencil_Yield_Triangles
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[1]: ChevronRegion
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[2]: Stencil_ArrowType4R
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[3]: Stencil_Bicycle2
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[4]: StopSign
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[5]: Stencil_STOP
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Assembly2
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: SolidSingleYellow
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[1]: SolidSingleWhite
RoadManager.cpp / 2666 / roadmanager::OpenDrive::LoadOpenDriveFile(): unknown road signal type: 206 (road ids=45)

RoadManager.cpp / 1468 / roadmanager::Road::AddSignal(): Add signal[0]: Sign_Stop
RoadManager.cpp / 1468 / roadmanager::Road::AddSignal(): Add signal[1]: Sign_RightOnly
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Metal_CylinderPost_12ft
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Stencil_Bicycle2
RoadManager.cpp / 1468 / roadmanager::Road::AddSignal(): Add signal[0]: Sign_DoNotEnter
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Metal_CylinderPost_10ft
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 58 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: LadderCrosswalk-4
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[1]: LadderCrosswalk-4
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[2]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Assembly3
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: RoundBridgePost
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: LadderCrosswalk-4
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Assembly3
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[1]: StripedRegion
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[2]: SolidSingleWhite
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 85 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: LadderCrosswalk-3
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: StripedRegion yellow
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[1]: Assembly2
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[2]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: LadderCrosswalk-4
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Stencil_Bicycle2
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: LadderCrosswalk-3
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[1]: Stencil_Yield_Triangles
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[2]: LadderCrosswalk-4
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: StopSign
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[1]: Assembly3
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: LadderCrosswalk-3
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[1]: Assembly3
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[2]: SolidSingleWhite
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Stencil_Bicycle2
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 133 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Stencil_ArrowType1Short
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[1]: Stencil_Bicycle1
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 136 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Stencil_STOP
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[1]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[2]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[3]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[4]: Stencil_Bicycle2
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[5]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[6]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[7]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[8]: Stencil_Parking1
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 140 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[1]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[2]: Stencil_Bicycle2
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[3]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[4]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[5]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[6]: Stencil_Parking1
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 144 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 144 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 144 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Stencil_ArrowType1Short
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[1]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[2]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[3]:
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[4]: Stencil_Bicycle1
RoadManager.cpp / 1468 / roadmanager::Road::AddSignal(): Add signal[0]: StopLine
RoadManager.cpp / 1468 / roadmanager::Road::AddSignal(): Add signal[1]: StopLine
RoadManager.cpp / 1468 / roadmanager::Road::AddSignal(): Add signal[2]: StopLine
RoadManager.cpp / 1468 / roadmanager::Road::AddSignal(): Add signal[3]: StopLine
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Stencil_Parking1
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Assembly1
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 153 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 153 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Stencil_STOP
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[1]: Stencil_STOP
RoadManager.cpp / 2541 / roadmanager::OpenDrive::LoadOpenDriveFile(): No road mark created for road 157 lane 0. Type 4 not supported. Either swich type or add a roadMark <type> element.
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Stencil_BUS
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: Stencil_Bicycle2
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[0]: LadderCrosswalk-4
RoadManager.cpp / 1489 / roadmanager::Road::AddObject(): Add object[1]: StopSign
RoadManager.cpp / 4529 / roadmanager::OpenDrive::SetRoadOSI(): Generating OSI lanes
RoadManager.cpp / 4531 / roadmanager::OpenDrive::SetRoadOSI(): Generating OSI road marks
RoadManager.cpp / 4533 / roadmanager::OpenDrive::SetRoadOSI(): Generating OSI lane boundaries
RoadManager.cpp / 4535 / roadmanager::OpenDrive::SetRoadOSI(): OSI road features done
viewer.cpp / 716 / viewer::Viewer::Viewer(): Anti-Aliasing number of subsamples: 4
viewer.cpp / 871 / viewer::Viewer::Viewer(): No scenegraph 3D model loaded. Generating a simplistic one...
osi_features: lines off points off
0 cars added
`

**Comment by eknabevcc** [comment] 2021-03-10 09:26
I see. That was both good and bad news...

Yes, I can now see that it seems to fail after window is created. So it must be something else. It would be good to find the issue.

The best way forward would be if you could provide any OpenDRIVE file that cause such a crash. 
If you don't want to share as is would it be possible to try trim it down to a minimum? Maybe just include one road element or so...

**Comment by eknabevcc** [comment] 2021-03-26 07:30
Just a reminder: If issue remains, I would be happy to fight it. However then I need the OpenDRIVE (or at least part of it) in order to reproduce and hunt down the problem.
Otherwise we'll not know whether the issue is in esmini or in the OpenDRIVE file (in which case esmini should catch and provide better warning). 
If you can't provide the OpenDRIVE for any (probably good) reason, I suggest we close the issue due to "end of road".

**Comment by TKeutgens** [comment] 2021-03-26 08:40
Thank you for the reminder. The problem still persists. 

Please find attached the OpenDRIVE file that causes the problem.
[esmini_test_scene_xodr.zip](https://github.com/esmini/esmini/files/6210400/esmini_test_scene_xodr.zip)

**Comment by eknabevcc** [comment] 2021-03-26 11:59
Ah, I found it - thanks for providing the odr! There was a bug in odrviewer that the camera tried to follow first vehicle even if it was not present. I don't remember exactly, but it was fixed a few versions ago. I tried with 2.3.0 (same as you) and got the same crash as you. When I'm running with current version (https://github.com/esmini/esmini/releases/latest) it works better.

So please download latest release and try again.

**Comment by eknabevcc** [comment] 2021-04-07 19:49
Did you have a chance to test an updated odrviewer?

**Comment by TKeutgens** [comment] 2021-04-12 17:51
Hi @eknabevcc, sorry for the late reply. I've testet the map with the newest version of Esmini 2.6.1 and the visualization works great. What is not working is the addition of vehicles to the scene. 

As I don't need this feature, it's ok with me to close this issue.

**Comment by eknabevcc** [comment] 2021-04-13 04:55
Thanks for update. Then I'll  close it.
Regarding missing vehicles, I think the reason might be short road. To populate cars on short roads you need to increase --density heavily. But as you say, usually you don't need driving vehicles on small roads. It's more useful for road networks where you want to debug/test connectivity, e.g. off-ramps and intersections. The idea is that random traffic will find its way and indicate what connections works properly.

**Closed by eknabevcc** 2021-04-13 04:55 UTC
