### ISSUE TITLE
FollowTrajectory, Vehicle's heading become reverse 

### ISSUE THREAD

**Issue by GraySnail** [esmini/esmini#21] opened 2020-06-03 09:16 UTC
I play my scenarios based on FollowTrajectoryAction, in every vertex of trajectory, include a WorldPosition node. I hava some issue:
1. In different coordinate (inertial, track and lane), headings are same. But in OpenSCENARIO identification， its may be different. 
```
RoadManager.cpp / 3902 / PrintTrackPos(): 	Track pos: (road_id 120, s 16.71, t 7.66, h -1.63)
RoadManager.cpp / 3907 / PrintLanePos(): 	Lane pos: (road_id 120, lane_id 3, s 16.71, offset -1.09, h -1.63)
RoadManager.cpp / 3912 / PrintInertialPos(): 	Inertial pos: (x -7.71, y 31.71, z 0.00, h -1.63, p 0.00, r 0.00)
```

2. When the action completed, the vehicle's heading become reverse.

**Comment by esmini** [comment] 2020-06-03 13:10
Thanks a lot for this input! To simplify investigation, would it be possible for you to share the oscx-file, or at least the FollowTrajectoryAction, including the Trajectory definition (or at least a part of it, including just a few vertices)?

**Comment by GraySnail** [comment] 2020-06-04 03:07
Thanks for your attention.
[FollowTrajectoryAction.zip](https://github.com/esmini/esmini/files/4727256/FollowTrajectoryAction.zip)

**Comment by GraySnail** [comment] 2020-06-04 03:16
Tanks for your attention! Attach files include  xodr-file,  xosc-file and diagram of scenario.
[FollowTrajectoryAction.zip](https://github.com/esmini/esmini/files/4727288/FollowTrajectoryAction.zip)

**Comment by esmini** [comment] 2020-06-04 08:33
Great finding, and excellent that you provided the zip - which really helped finding issue and solution!
I hope the problem is fixed now, by commit [Fix issue 21](https://github.com/esmini/esmini/commit/650d3346ebc56e72b8196583cd4db30d43af2f66)

**Comment by esmini** [comment] 2020-06-04 08:36
By the way, the behavior is as follow: when reaching the end of a trajectory, it will align the heading of the entity/vehicle to the road heading, whatever direction is closest forward or backward.

**Closed** 2020-06-10 06:26 UTC
