### ISSUE TITLE
xodr file can't be visualized correctly when the scenario runs

### ISSUE THREAD

**Issue by zhuyingxiang95** [esmini/esmini#394] opened 2023-02-13 17:32 UTC
the xodr file looks perfectly in oxdr viewer. but when i run a xosc basing on it, then the lane mark of generated 3D geometry model looks in a mess. can someone give me some advices about how to fix this bug?

**Comment by eknabevcc** [comment] 2023-02-13 18:55
We don't know about this problem. Please provide an OpenDRIVE and OpenSCENARIO file that cause this issue, and we will investigate.

**Comment by csawp** [comment] 2023-02-22 06:11
I have also encountered this problem. It should be caused by too large coordinates. You can base the coordinate origin on 0 and add a coordinate offset to solve this problem

**Comment by eknabevcc** [comment] 2023-02-22 06:55
Thanks @csawp for potential root cause. I didn't even think about that possibility. I've seen a similar (#93) with distant coordinates causing zig zag patterns in odrplot (in that case fixed by adding decimals). 

But I'm a bit puzzled that the road looks different in odrviewer and esmini...
I tested with this simplistic road:
[arc.xodr.txt](https://github.com/esmini/esmini/files/10800775/arc.xodr.txt)
It has a single arc road starting at x=10 000 000, y=10 000 000 (1e+7, 1e+7).
I got similar issues in odrviewer and esmini. Looks like:
![img_1e7](https://user-images.githubusercontent.com/29146839/220543815-381047e2-7c23-410d-ac14-998bffa55269.jpg)

Changing start position to 1e+6, 1e+6:
![img_1e6](https://user-images.githubusercontent.com/29146839/220543791-64952114-d394-47cd-9728-63fad2b16e45.jpg)

So obviously there is something happening with the floating point precision at that distance from origin.

It's not many use cases that require such a large environment, so I agree with @csawp: Try define a local coordinate system for the scenario in esmini, moving it closer to origin. 

Let us know if this is not the root cause in your case, in which case I'd like to further investigate. But we need more input, like a snippet of an OpenDRIVE causing the problem.

**Comment by csawp** [comment] 2023-02-22 07:08
In fact, I suggest that this function be automatically analyzed in the RoadManage file. When the first Road object comes, save the XY and then based on the 0 point. After all the saved values are subtracted from the subsequent Roads, it is equivalent to that they all have their own local coordinates. If the offset value is automatically added, there will be no problem of losing the floating point precision due to the large coordinates

**Comment by eknabevcc** [comment] 2023-02-22 07:20
Potentially a good idea. But in the end the true (large) coordinates would be used for log files, API calls, controllers and so on, where they might cause issues anyway. So the recommendation is to define the scenario in a reasonable local coordinate system and do any necessary transformations outside esmini.

It might be that we'll reconsider this later, e.g. to support geographical coordinates. But for time being we will not prioritize automatic re-location of the scenario. Although pull-requests are always welcome and considered.

**Comment by csawp** [comment] 2023-02-22 07:30
In fact, this is a small problem. Has the author's ESMINI considered OPENCL and CUDA to calculate the core running car problem? It will be too laggy when trying to simulate many cars

**Comment by eknabevcc** [comment] 2023-02-22 07:35
Can you please elaborate what is "core running car problem"?
We haven't seen limitations in esmini wrt many cars. How do you define the actions for the many cars? Maybe it's a scenario design issue? How many cars are considered?

**Comment by csawp** [comment] 2023-02-22 07:44
![image](https://user-images.githubusercontent.com/114643211/220554589-0b04c707-6b5c-42eb-aa7b-fbd9d042d487.png)
This function car is too many to get stuck. I have seen all the objects enumerated in the code. My idea is to save the current objects in the surrounding range every 0.3 seconds, or this function with a large amount of computation is handed to OPENCL or CUDA for calculation

**Comment by eknabevcc** [comment] 2023-02-22 07:55
Here's an example running ~2000 cars in odrviewer (on a simple laptop)
https://youtu.be/XONOW7H_vv4

We haven't had actual scenarios with this number of cars. Nonetheless the example shows that the OSG based visualization is not a bottleneck for this number of cars. But of course, this is a simple use. E.g. coordinates are not transformed from world to road coordinates, which would be the case for some scenario actions.

That said, we're now and then doing optimizations to support actual needs. So if you have an actual scenario causing performance issues, please share it (or an equivalent if the original is confidential) for our analysis. 

Outsourcing computations to GPU is a cool idea (if capabilities available, not always in cluster nodes e.g.). But I'd start finding out what is the bottle neck first. Maybe it's something easily fixed by optimization.

Ah, now I see your code example. The "Delta" function could be expensive, especially with many cars around also depending on the complexity of the road network. 

This is good example example where some optimization could do magic. E.g. culling vehicles based on euclidean distance (x, y) as a first rough step, maybe even keeping track of how often the distance needs to be updated based on last registered distance. Then use the Delta function which will find distances based on found closest route in the road network.

**Comment by csawp** [comment] 2023-02-22 07:59
There is no collision check, no acceleration or deceleration in your case
![image](https://user-images.githubusercontent.com/114643211/220558121-986d89b4-75de-496e-85a1-0da8a8c9b101.png)
This case is run separately without analyzing other vehicles

**Comment by eknabevcc** [comment] 2023-02-22 08:07
Exactly, I just wanted to show that it's typically not the graphics system that is the bottleneck or the number of entities itself. 

For more functionality you have to be careful for large scale scenarios. As explained, some calculations are too complex to be performed on all entities. And most cases you don't need to. By some simple optimization of the application code, e.g. as outlined in last comment, you can increase number of entities by large numbers.

We can support further if you have an actual issue, but then we need a scenario and, when applicable, application code to reproduce the problem. Otherwise it will be just rough advices like above.

**Comment by csawp** [comment] 2023-02-22 08:12
So be it, at present, ControllerACC can run 100 cars, ControllerALKS_ R157SM can run 20 cars. Thank you for your reply. I hope ESMINI will do better and I will always pay attention to it

**Comment by eknabevcc** [comment] 2023-02-22 08:15
esmini is continuously improving 🙂

Closing the issue now. Please add info for further questions, we can then re-open.

**Closed by eknabevcc** 2023-02-22 08:15 UTC
