### ISSUE TITLE
Example of 'Driver model' - 'test-driver.xosc'

### ISSUE THREAD

**Issue by ZhangZongshi-Catarc** [esmini/esmini#102] opened 2021-04-19 07:06 UTC
Could you please provide me the file 'test-driver.xosc '? 

I can't open the link provided. [https://www.dropbox.com/s/h9uqj2la4sk2t2o/test-driver.xosc?dl=1](url)

Thank you very much!

Best Regard
Zongshi

**Comment by eknabevcc** [comment] 2021-04-19 07:58
It should work, perhaps the link is wrong. Please try again:
[https://www.dropbox.com/s/h9uqj2la4sk2t2o/test-driver.xosc?dl=1](https://www.dropbox.com/s/h9uqj2la4sk2t2o/test-driver.xosc?dl=1)

**Comment by eknabevcc** [comment] 2021-04-19 08:00
Please let me know if link still is not accessible for you. Here's the file in worst case (remove postfix ".txt"):
[test-driver.xosc.txt](https://github.com/esmini/esmini/files/6334236/test-driver.xosc.txt)

**Comment by ZhangZongshi-Catarc** [comment] 2021-04-19 08:05
Thank you for your support!
I can download 'test-driver.xosc.txt' now, but still can't open the link [https://www.dropbox.com/s/h9uqj2la4sk2t2o/test-driver.xosc?dl=1](url)

please be aware.  : )

**Comment by eknabevcc** [comment] 2021-04-19 08:35
Thanks for info.
It (the link) should not open a page, but automatically download the file.

If you put a 0 (instead of a 1) at the end, you will actually go to a page, where you get an option to download the file (and some info that it couldn't be previewed).

Could you please try this one:
https://www.dropbox.com/s/h9uqj2la4sk2t2o/test-driver.xosc?dl=0
It would be valuable for us to know the result.

**Comment by ZhangZongshi-Catarc** [comment] 2021-04-20 09:16
The new link is not available as well. I can't open this page.

**Comment by eknabevcc** [comment] 2021-04-20 10:47
Interesting. I don't understand. The URL exist. This is what I get from the latest link (dl=0):
![preview](https://user-images.githubusercontent.com/29146839/115383755-84eb0480-a1d6-11eb-9bab-e05760448ba1.jpg)
As you can see there is a Download button. 
Can you please share, e.g. screenshot, how it looks when you try to access the link? Then we can potentially understand if the issue is on our side. Potentially the DropBox service is blocked for you for some reason.

**Comment by eknabevcc** [comment] 2021-04-20 10:52
Interesting. Thanks for trying. I don't understand. The URL exist. This is what I get from the latest link (dl=0):

![preview](https://user-images.githubusercontent.com/29146839/115384101-edd27c80-a1d6-11eb-8187-937d5d1c6a5b.png)

As you can see (hope you see the image) there is a Download button (under the text "xosc: fils can't be previewed").

Can you please share, e.g. screenshot, how it looks when you try to access the link? 
Then we can potentially understand if the issue is on our side. Potentially the DropBox service is blocked for you for some reason.

**Comment by ZhangZongshi-Catarc** [comment] 2021-04-21 00:45
The browser keeps loading but no result.
<img width="1437" alt="截屏2021-04-21 上午8 43 53" src="https://user-images.githubusercontent.com/82502945/115480850-f336d200-a27d-11eb-9e8a-12969ce262a4.png">

**Comment by eknabevcc** [comment] 2021-04-21 04:49
Ok. Thanks for testing again👍. It seems to be some issue at your end. DropBox is usually not causing problem like this. I'll keep this in mind if I hear of more similar cases. Other than that there is not much we can do. Luckily this is not a critical problem since individual files can be shared other ways.
So we reach end of road of this issue. And you got the xosc file. So I close this for now.

**Closed by eknabevcc** 2021-04-21 04:49 UTC
