### ISSUE TITLE
Missing accessors in RMObject

### ISSUE THREAD

**Issue by dalishi** [esmini/esmini#109] opened 2021-05-01 09:43 UTC
Hi, the class RMObject in RoadManager does not have functions that can return the following features of an object:
1. type
2. id
3. length
4. width
5. pitch
6. roll

Is there a plan to add these interfaces? Thanks.

**Comment by eknabevcc** [comment] 2021-05-03 06:49
Good idea, don't really know why they were missing. Anyway, now they are added from commit https://github.com/esmini/esmini/commit/bcb991141c8b3797dc7a659c9ac813b0cd8da695.
And will be part of next release.
Thanks for reporting the gap.

**Comment by eknabevcc** [comment] 2021-05-12 07:11
Included in release [2.8.1](https://github.com/esmini/esmini/releases/tag/v2.8.1)
Please let us know the result if you get a chance to test it.

**Comment by kunnalparihar** [comment] 2021-05-14 05:22
I also faced the same issue with the older version. For the new release, the issue is now solved. thanks

**Comment by eknabevcc** [comment] 2021-05-14 05:38
Thanks @kunnalparihar for testing and reporting OK. And thanks @dalishi for reporting in first place. 👍
I close the issue now.

**Closed by eknabevcc** 2021-05-14 05:38 UTC
