### ISSUE TITLE
combination addEntityAction with sumo

### ISSUE THREAD

**Issue by wilbertzhohn** [esmini/esmini#308] opened 2022-07-20 18:38 UTC
Hey, 
I try to simulate multiple road users (controlled via actions and triggers within the xosc-file) in combination with a sumo-controller for other vehicles.
Generally, it seems possible, but I do get to errors (which are distinct to my best knowledge) in specific situations:
1. If a vehicle (which is not controlled by sumo) enters a new road/ lane segment, it disappears although it would not without sumo and alhtough it has a specific (longer trajectory)
2. If new vehicles are added (via addEntityAction) while sumo is running, the program crashes few milliseconds after finishing the AddEntityAction and throwing the error: "Gateway did not provide state for external car 5"

Are those errors or is it just not possible to combine the sumo controller with normal xosc conditions and actions?

I would be glad if you could help me fixing this!

**Comment by eknabevcc** [comment] 2022-08-08 06:48
It sure seems like you found a few bugs. The SUMO integration is not very well tested. So your input is valuable.

Would it be possible for you to share a scenario causing these two issues to simplify/speed-up investigation on our side? The simpler the better.

**Comment by wilbertzhohn** [comment] 2022-08-08 08:35
Unfortunately, I can not give you the map with the issue, so I created a new scenario on the fabriksgatan-map.
Here, (as far as I see) do not get the same errors as descriped above, but still have issues with the combination (e.g. getting error messages when trying to control vehicles via usual xosc-commands - and sometimes it does not work at all).
[sumo_integration_test.zip](https://github.com/esmini/esmini/files/9280246/sumo_integration_test.zip)

I would be glad if you could have a look at it. Maybe, it also helps/ interferes with the issues I descriped above.

**Comment by eknabevcc** [comment] 2022-08-09 06:16
First: To have a smoother update of SUMO vehicles you can add:
`<step-length value="0.01" />`
to the `<time>` section in the .sumocfg file. Like in this: [e6mini.sumocfg](https://github.com/esmini/esmini/blob/master/resources/sumo_inputs/e6mini.sumocfg).

Now regarding the issues:

**1. Non SUMO vehicles are removed at end of road.** 
Even non SUMO vehicles, i.e. vehicles created by esmini (from the OpenSCENARIO description), are registered within SUMO in order to be visible for the SUMO virtual drivers (avoiding collisions etc.). In SUMO when a vehicle reach end of route it has reach the goal and will simply be removed. 

Currently esmini do not assign SUMO routes to esmini vehicles when being registered in SUMO. I assume that's the reason why SUMO consider the current road as the "route", and when reaching end of road the goal is reached - and it's removed.

I think there are potential solutions for this issue (using features in the SUMO API or simply re-register deleted esmini vehicles), but we haven't investigated yet. Simply because other things has been prioritized. 

**2. Crash after Add/Delete entity actions**
I found two issues in esmini. 1: If an esmini object is referred to by the storyboard, i.e. has some actions assigned to it, there will be a crash after object is deleted. 2: esmini vehicles are only added initially in the start of the SUMO controller. Not handling the case where vehicles are added later in the scenario. 

These two issues have hopefully been solved by commit [a1126e8](https://github.com/esmini/esmini/commit/a1126e8dd1b8bdcdc9d147278aa9c9341b919036).

I created a branch for this commit: [sync_sumo_obj_list](https://github.com/esmini/esmini/tree/sync_sumo_obj_list).

Would it be possible for you to test this branch with your challenging scenario? If you have a local esmini code clone you would write:
`git pull` (to get the latest, including branches)
`git checkout sync_sumo_obj_list` (to switch to the branch)
Then build as usual.

Otherwise I could probably provide the executable for you. At least if you are you running on Windows or Linux.

**Comment by wilbertzhohn** [comment] 2022-08-09 07:11
Thank you for your fast response!
I do know the step size, but just created a new file quite quickly. I hope it was fine for you.

1. Thanks for your explanation. I do understand the issues caused by the API and that there are also other issues. Generally, I think there is a great potential combining xosc-commands and esmini for a smooth and robust road user behavior, so I would be really glad, if you could have a look at it (when you have time).

2. I´d like to test it, but on my actual computer I can not compile it easily, so that I would be glad if you could send me the binary files (windows). I am really looking forward to test your fix.

**Comment by eknabevcc** [comment] 2022-08-09 07:48
I agree. It would be very nice to improve the SUMO/esmini integration, it has a great potential. However, at the moment we can't prioritize that task. But it (the need) can change rapidly. And perhaps there are esmini users && SUMO gurus out there that can help or at least have ideas on the integration.

I put an esmini executable for Windows [here](https://www.dropbox.com/s/mwxbnyilhk3tlwu/esmini.exe?dl=1).

Please try and provide feedback how it works wrt add/delete crashes.

**Comment by wilbertzhohn** [comment] 2022-08-09 08:49
I tried it out and the program does not crash on a traditional way. When I test the xosc-file with my map (an intersection with a couple of road/ lanes), a vehicle is removed changing roads, afterwards added again after approx. 0.02sec and when it reaches the next road boarder, it is reseted to the original point and crashes (with no error message) 1 second later

**Comment by eknabevcc** [comment] 2022-08-09 10:59
I see. I think the order of adding/removing vehicles was bad.

I updated the exe file. Please get [it](https://www.dropbox.com/s/mwxbnyilhk3tlwu/esmini.exe?dl=1) and try again.

**Comment by wilbertzhohn** [comment] 2022-08-09 11:06
Now, first of all (at 0.000 the existing vehicles are added to sumo. After .127sec the vehicle is removed (although it shouldnt) - (velocity independent - so I assume, that it does not depend on entering a new road)

**Comment by eknabevcc** [comment] 2022-08-09 12:40
The first thing, vehicles are added to SUMO at 0.0 is correct behavior, also any SUMO vehicles should be added to the scenario.

Then regarding .127 removed vehicle: I think SUMO has another criteria, like if a vehicle is still or comes to a stop (speed close to zero), then it is removed as well. Hard for me to understand what's happening. To move forward in an efficient way we need a way to reproduce the issue you see. 

It would be great if the issue could be reproduced with the fabriksgatan.xodr. To make it deterministic you can add two arguments: `--fixed_timestep <time>` and `--seed <number>`

My suggestion is:
1. Decide on a timestep, e.g. 0.05
2. Then run the scenario, over and over, until the issue happens. E.g: 
`./bin/esmini --window 60 60 800 400 --osc ./resources/tmp/sumo-test_issue.xosc --fixed_timestep 0.05`
3. When the bug happens, look for `Generated seed <number>` in the console output (almost at top) and make a note of the seed number.
4. To verify reproduction, run again with specified seed, e.g:
5. `./bin/esmini --window 60 60 800 400 --osc ./resources/tmp/sumo-test_issue.xosc --fixed_timestep 0.05 --seed 2679495628`

Then just tell me the timestep and seed, and I can reproduce and debug easily. 👍

**Comment by eknabevcc** [comment] 2022-09-27 15:03
Merged fixes so far to master. Remaining "issues" probably according to sumo default behavior.
Closing due to inactivity.

**Closed by eknabevcc** 2022-09-27 15:03 UTC

**Comment by wilbertzhohn** [comment] 2022-10-10 13:47
I am sorry for not replying for such a long time because of other work.

Thank you for your fixes. I think it already helps a lot.
