### ISSUE TITLE
Esmini ALKS controller cannot work as expected to control the ego car in both longitudinal and lateral directions.

### ISSUE THREAD

**Issue by Iqbalparvi** [esmini/esmini#291] opened 2022-06-16 04:09 UTC
I am trying to visualize and repeat a simulation test scenario for the Lane Keeping Assist System (LKAS). The original scenario is by MATLAB: https://au.mathworks.com/help/mpc/ug/lane-keeping-assist-with-lane-detection.html, where a predefined careless driving path can be corrected by the LKAS controller in the actual simulation.
To build this scenario by Esmini and openscenario, we export a road and some waypoints from the MATLAB Simulink platform and assign a FollowTrajectoryAction to the ego car while letting an Esmini ALKS controller control the ego car in both longitudinal and lateral directions. But it does not work as expected. (I wonder if such predefined careless routing actions can be overridden by the controller in any way? Or shall the ego car strictly follow the route without having any chance for the controller to take over?)

Could anyone please have a look at our openscenario and opendrive files? And any insight will be appreciated. 

Many thanks!
[scenario files.zip](https://github.com/esmini/esmini/files/8915582/scenario.files.zip)

**Comment by mander76** [comment] 2022-06-20 08:24
Some comments about the scenario itself: 
1. you are not activating the controller in the longitudinal domain (it is set to false)
2. you are actually overwriting the trajectory with the ControllerAction, since you have it in the same Maneuver with an overwrite priority in the Event. 
Some things that will change the behavior of the scenario:
- If you put the ControllerAction priority to parallell
- Move the ControllerAction to it's own Maneuver
- Activate the controller before the trajectory action (since this one has priority = parallel)

**Comment by Iqbalparvi** [comment] 2022-06-20 12:06
Hi @mander76 ;
Thanks for your comments and guidance.
We have made all the changes accordingly but the lane-keeping controller still not works as expected.
I uploaded the modified Open Scenario for review and a figure to show what we want, i.e. a careless trajectory can be corrected by the controller in the lateral direction.
[newFiles.zip](https://github.com/esmini/esmini/files/8940410/newFiles.zip)

**Comment by eknabevcc** [comment] 2022-09-19 06:45
Wrt lateral behavior your scenario was correct already in first version:

* The SetLongAndLateralControl event is started first (time = 1). Then at time = 2 you start the FollowTrajectoryPLineEvent with priority = parallel, which will make it run in parallel to the controller action. 

* In this case I understand that you're interested in the lateral domain, which I guess explains why you only activated the controller on that domain. Anyway, 

So far so good. Now to the bad news: 
Current ALKS controllers in esmini do not apply advanced (dynamic) lateral control. It will only keep current lane offset.
In your scenario the trajectory will continuously change the lateral offset and the ALKS will just stick to latest value. This is the main reason why you don't see the expected behavior of ALKS steering back to lane center.

This is a very interesting but tricky use case, also discussed in more detail in issue #304, why I suggest to close this issue.

**Comment by Iqbalparvi** [comment] 2022-09-20 01:22
Thank you so much for your re-attention to our discussion related to the ALKS controller.I will close this issue here and will consider the related issue #304 for further comments.

**Closed** 2022-09-20 01:22 UTC
