### ISSUE TITLE
osi-trace saving empty

### ISSUE THREAD

**Issue by olcayakgn** [esmini/esmini#310] opened 2022-07-22 12:24 UTC
Did anyone experience that saved osi ground truth data is empty? I am using the following command line prompt to save osi data;

```sh
./bin/esmini --window 60 60 800 400 --osc ./resources/xosc/cut-in.xosc --osi_file
```

My terminal output;

```sh
./bin/esmini --window 60 60 800 400 --osc ./resources/xosc/cut-in.xosc --osi_file
esmini GIT REV: 3d1abcd
esmini GIT TAG: 
esmini GIT BRANCH: master
esmini BUILD VERSION: N/A - client build
Generated seed 4255366965
Loading ./resources/xosc/cut-in.xosc (v1.1)
Unsupported geo reference attr: +no_defs
Unsupported object type: rail-pole - interpret as NONE
Unsupported object type: rail-pole - interpret as NONE
Unsupported object type: guide-post - interpret as NONE
Unsupported object type: guide-post - interpret as NONE
Loaded OpenDRIVE: ./resources/xosc/../xodr/e6mini.xodr
Expr ${250/3.6} = 250/3.6 = 69.4444444444
Expr ${$EgoSpeed / 3.6} = 108 / 3.6 = 30.0000000000
7 parameters:
   TargetSpeedFactor = 1.2
   EgoSpeed = 108
   HeadwayTime_Brake = 0.7
   HeadwayTime_LaneChange = 0.4
   EgoStartS = 50
   TargetVehicle = car_red
   HostVehicle = car_white
0.000: OSI tracefile ground_truth.osi opened
Invalid MIT-MAGIC-COOKIE-1 key0.000: Loaded scenegraph: ./resources/xosc/../models/e6mini.osgb
0.000: Object ../models/railing-pole.osgb missing length, set to bounding box length 0.10
0.000: Object ../models/railing-pole.osgb missing width, set to bounding box width 0.10
0.000: Object ../models/railing-pole.osgb missing height, set to bounding box height 1.00
0.000: Object ../models/railing-pole.osgb missing length, set to bounding box length 0.10
0.000: Object ../models/railing-pole.osgb missing width, set to bounding box width 0.10
0.000: Object ../models/railing-pole.osgb missing height, set to bounding box height 1.00
0.000: Object ../models/railing.osgb missing length, set to bounding box length 4.00
0.000: Object ../models/railing.osgb missing width, set to bounding box width 0.10
0.000: Object ../models/railing.osgb missing height, set to bounding box height 0.20
0.000: Object ../models/railing.osgb missing length, set to bounding box length 4.00
0.000: Object ../models/railing.osgb missing width, set to bounding box width 0.10
0.000: Object ../models/railing.osgb missing height, set to bounding box height 0.20
0.000: Object ../models/guide-post.osgb missing length, set to bounding box length 0.08
0.000: Object ../models/guide-post.osgb missing width, set to bounding box width 0.13
0.000: Object ../models/guide-post.osgb missing height, set to bounding box height 1.25
0.000: Object ../models/guide-post.osgb missing length, set to bounding box length 0.08
0.000: Object ../models/guide-post.osgb missing width, set to bounding box width 0.13
0.000: Object ../models/guide-post.osgb missing height, set to bounding box height 1.25
0.000: Adjusted Ego bounding box to model car_white.osgb - xyz: 1.46, 0.00, 0.77 lwh: 5.04, 2.04, 1.49
0.000: Adjusted OverTaker bounding box to model car_red.osgb - xyz: 1.46, 0.00, 0.77 lwh: 5.04, 2.04, 1.49
0.000: Starting teleport Action
0.000: Ego New position:
0.000: Pos(8.17, 49.97, -0.04) Rot(1.57, 0.00, 0.00) roadId 0 laneId -3 offset 0.00 t -8.00
0.000: Init Ego TeleportAction standbyState -> startTransition -> runningState
0.000: Init Ego LongitudinalAction standbyState -> startTransition -> runningState
0.000: Starting teleport Action
0.000: OverTaker New position:
0.000: Pos(4.51, 24.98, -0.01) Rot(1.57, 0.00, 0.00) roadId 0 laneId -2 offset 0.00 t -4.42
0.000: Init OverTaker TeleportAction standbyState -> startTransition -> runningState
0.000: Init Ego TeleportAction runningState -> endTransition -> completeState
0.000: Init Ego LongitudinalAction runningState -> endTransition -> completeState
0.000: Init OverTaker TeleportAction runningState -> endTransition -> completeState
0.000: Gateway did not provide state for external car 0
0.000: Gateway did not provide state for external car 1
0.000: OSIReporter::UpdateOSIStationaryObjectODR -> Unsupported stationary object category
0.000: OSIReporter::UpdateOSIStationaryObjectODR -> Unsupported stationary object category
0.000: OSIReporter::UpdateOSIStationaryObjectODR -> Unsupported stationary object category
0.000: OSIReporter::UpdateOSIStationaryObjectODR -> Unsupported stationary object category
0.001: Trigger /------------------------------------------------
0.001: CutInActStart == true, 0.0010 > 0.00 edge: none
0.001: Trigger  ------------------------------------------------/
0.001: CutInManeuver standbyState -> startTransition -> runningState
0.001: CutInAndBrakeSequence standbyState -> startTransition -> runningState
0.001: CutInAndBrakeAct standbyState -> startTransition -> runningState
0.001: Trigger /------------------------------------------------
0.001: OverTakerStartSpeedCondition == true, element: CutInAndBrakeAct state: START_TRANSITION, edge: none
0.001: Trigger  ------------------------------------------------/
0.012: OverTakerStartSpeedAction standbyState -> startTransition -> runningState
0.012: OverTakerStartSpeedEvent standbyState -> startTransition -> runningState
6.182: Trigger /------------------------------------------------
6.182: CutInStartCondition == true, HWT: 0.40 > 0.40, edge rising
6.182: Triggering entity 0: Ego
6.182: Trigger  ------------------------------------------------/
6.182: OverTakerStartSpeedEvent complete after 1 execution
6.182: Event OverTakerStartSpeedEvent ended, overwritten by event CutInEvent
6.199: OverTakerStartSpeedAction runningState -> endTransition -> completeState
6.199: OverTakerStartSpeedEvent runningState -> endTransition -> completeState
6.199: CutInAction standbyState -> startTransition -> runningState
6.199: CutInEvent standbyState -> startTransition -> runningState
7.681: Trigger /------------------------------------------------
7.681: BrakeCondition == true, HWT: 0.70 > 0.70, edge rising
7.681: Triggering entity 0: Ego
7.681: Trigger  ------------------------------------------------/
7.681: Event(s) ongoing, OvertakerBrakeEvent will run in parallel
7.698: OvertakerBrakeAction standbyState -> startTransition -> runningState
7.698: OvertakerBrakeEvent standbyState -> startTransition -> runningState
9.197: CutInEvent complete after 1 execution
9.214: CutInAction runningState -> endTransition -> completeState
9.214: CutInEvent runningState -> endTransition -> completeState
16.664: OvertakerBrakeEvent complete after 1 execution
16.681: OvertakerBrakeAction runningState -> endTransition -> completeState
16.681: OvertakerBrakeEvent runningState -> endTransition -> completeState
16.681: CutInAndBrakeSequence complete after 1 execution
16.699: ActStopCondition timer 5.00s started
16.699: CutInManeuver runningState -> endTransition -> completeState
16.699: CutInAndBrakeSequence runningState -> endTransition -> completeState
21.712: ActStopCondition timer expired at 5.01 seconds
21.712: Trigger /------------------------------------------------
21.712: ActStopCondition == true, element: CutInManeuver state: END_TRANSITION, edge: rising
21.712: Trigger  ------------------------------------------------/
21.712: CutInAndBrakeAct runningState -> endTransition -> completeState
21.729: All acts are done, quit now
Closing

```

**Comment by eknabevcc** [comment] 2022-08-08 06:43
Can't reproduce. 

Running:
`./bin/esmini --window 60 60 800 400 --osc ./resources/xosc/cut-in.xosc --fixed_timestep 0.05 --osi_file`

I get `ground_truth.osi` of size 271 KB.

Can you please run the exact same command (including the fixed_timestep argument) and check again for the `ground_truth.osi`. Is it completely missing? Is it empty (size = 0)? Or is it something wrong with the content?

If empty or missing, what platform do you run? If Linux, what version? (check with e.g. `uname -vior`)

**Comment by eknabevcc** [comment] 2022-08-27 09:05
Any input or close issue?

**Comment by eknabevcc** [comment] 2022-09-23 13:14
Assume issue solved. Closing.

**Closed by eknabevcc** 2022-09-23 13:14 UTC
