### ISSUE TITLE
Wrong headway time calculation on curved roads

### ISSUE THREAD

**Issue by arauschert** [esmini/esmini#139] opened 2021-08-02 12:02 UTC
Hi,

when testing the Crossing pedestrian ALKS scenario on a tightly curved road, I realized that the TimeHeadwayCondition is not evaluated as expected and only triggers once the car passes the pedestrian already. If you take the crossing pedestrian scenario from [this commit](https://github.com/asam-oss/OSC-ALKS-scenarios/pull/45/commits/7680a8e95e7eb80bfc96541ac957732c0ba46354) change the road to ALKS_Road_left_radius_250m.xodr, then you can reproduce the behaviour. 
I couldn't figure out, what goes wrong in the TimeHeadway calculation, but the road curvature is the only thing that changed and produced this behavior. What is obvious is that only at HWT=0 the condition is true and not already at HWT=3.59. With e.g. 1000m radius or a straight the scenario works fine.

Here's the logs:
30.469: Trigger /------------------------------------------------
30.469: CrossStartCondition == true, HWT: 0.00 < 3.60, edge rising
30.469: Triggering entity 0: Ego
30.469: Trigger  ------------------------------------------------/
30.494: CrossAction standbyState -> startTransition -> runningState
30.494: CrossEvent standbyState -> startTransition -> runningState
37.684: CrossEvent complete after 1 execution
37.701: CrossAction runningState -> endTransition -> completeState
37.701: CrossEvent runningState -> endTransition -> completeState

**Comment by eknabevcc** [comment] 2021-08-02 19:01
Yes, another good bug finding. The root cause was heading of entities not correctly taken into account when figuring out inter-displacement. TimeHeadway is undefined when target entity is concluded to be behind. 

In this scenario inter-displacement was at some duration found wrong -> resulting in undefined HWT -> resulting in incorrect triggering. 

It should now be fixed by commit d7ab1c931b3e7c741845a39851b64e40be398bfd. It would be great if you could test it. Let me know if you need a release up front. Otherwise I'll wait with the release until you find the fix OK.

**Comment by arauschert** [comment] 2021-08-03 06:52
Thanks a lot for the quick fix! Can you please tell me, where I can find the build artifacts of the CI for download? Didn'T see them in appveyor.

**Comment by eknabevcc** [comment] 2021-08-03 15:41
Release 2.12.4 will soon be [available](https://github.com/esmini/esmini/releases).

**Comment by arauschert** [comment] 2021-08-04 06:08
I tested it and it works. The issue can be closed.

**Closed** 2021-08-04 06:18 UTC
