### ISSUE TITLE
Cubic shape initial relative lane change does not work

### ISSUE THREAD

**Issue by johschmitz** [esmini/esmini#140] opened 2021-08-03 18:32 UTC
While working on implementing multi (more than 2) lane roads in [Blender Driving Scenario Creator](https://github.com/johschmitz/blender-driving-scenario-creator) I found that an initial relative lane change with a cubic shape does not work while it does work for a step shape. Or maybe I am doing something wrong? See attached example:

[initial_relative_lane_change.zip](https://github.com/esmini/esmini/files/6926319/initial_relative_lane_change.zip)

To reproduce run each one from within its sub-directory with:

    esmini --osc xosc/export.xosc --window 50 50 800 400

**Comment by eknabevcc** [comment] 2021-08-05 07:34
For me your scenarios seems to work just fine.

Here's a screenshot from step version (lane change already done):
![image](https://user-images.githubusercontent.com/29146839/128309192-147bf084-7ee9-4ab6-8db8-d6ba71e95796.png)

and here's from cubic (lane change ongoing):
![image](https://user-images.githubusercontent.com/29146839/128309522-15242ae3-971c-4518-abc8-d4eb61fd7ae9.png)

I'm using esmini v2.12.4. What version do you use? If old, could you try with the [latest](https://github.com/esmini/esmini/releases)? Just to narrow down the investigation.

**Comment by johschmitz** [comment] 2021-08-05 20:13
There seems to be no

    esmini --version

Could you add it in future versions?
Going to test with the latest version now.

**Comment by johschmitz** [comment] 2021-08-05 20:20
I was running version 2.8.0 and now with 2.12.4 the bug seems to have been solved already. So I guess this can be closed but consider adding the `--version` option.

**Comment by eknabevcc** [comment] 2021-08-06 11:54
Yes, good idea. I've added an `--version` option (commit 59ed3cf845b149b2acb10596f47a0fec92be7b98) that will just print version info and then quit. It will be part of next release.
Good news that the issue is gone with later versions 👍

**Closed by eknabevcc** 2021-08-06 11:54 UTC
