### ISSUE TITLE
Objects lightning / dark one side

### ISSUE THREAD

**Issue by hcLime** [esmini/esmini#339] opened 2022-10-28 09:51 UTC
Hello,

I encountered the problem of the dark side of the objects within esmini. 
I have tried different .osgb conversion settings, however at the end one side of the objects is still very dark. 

![image](https://user-images.githubusercontent.com/91853287/198558894-3d040f97-2a24-47f1-bd9c-dae756825763.png)

Can lighting be edited/modified within esmini?

**Comment by eknabevcc** [comment] 2022-10-28 13:25
Not as is. 
The light model is very simple: Pretty high ambient level (~0.8) and then one single point light (~0.9) to add some light dynamics, like mimic the sun. 
I think the problem is when the model material is not supporting the ambient contribution. Then all sides facing away from the point light get dark. 
The light is defined [here in viewer.cpp](https://github.com/esmini/esmini/blob/3f5a67c2423fbb660053abbd2472f18d4482f9b7/EnvironmentSimulator/Modules/ViewerBase/viewer.cpp#L1781). One possibility would be to add another point light. 

Another approach to manipulate the model ambient setting. Would it be possible to **share one example** model, like a single house or just a door or anything? I would be interested in investigating the model. And if I find no smooth solution of manipulating the model then I might try to add an optional additional light source. 

For your info, I've seen this issue before so probably it's not that the model is "wrong".

**Comment by Chodowi2021** [comment] 2022-10-28 14:35
Okay, many thanks for your reply.
I will share a simple model as an example. Currently barrier model looks as below.

![Capture](https://user-images.githubusercontent.com/91853287/198645881-7f2f554f-a806-49fa-bd71-d59b6ced39d7.JPG)

Please find attached barrier.osgb model and initial barrier.fbx model.

[Model.zip](https://github.com/esmini/esmini/files/9889274/Model.zip)

**Comment by eknabevcc** [comment] 2022-10-31 08:01
Thanks for providing the model file. I investigated it and found two potential solutions, described in [User guide - Lighting](https://esmini.github.io/#_lighting).

The first approach is to patch the material definition in the model itself. The second is to add custom lights to the scene. This new feature is included in release [v2.26.8](https://github.com/esmini/esmini/releases/tag/v2.26.8).

I hope at least one if these methods works for your case.

FYI: I had some problem with your model finding a good intensity level for additional light. For some reason it's faces gets fully lit/saturated even with low light intensity. The added light resulting in image 3 (in user guide) was created with the values: x, y, z, intensity = 2000, -6000, 8000, 0.006. I don't have time to investigate further.

**Comment by hcLime** [comment] 2022-11-11 10:18
Many thanks for that.
I have applied an additional light source as a solution.
It looks decent now.

**Comment by eknabevcc** [comment] 2022-11-11 10:27
Thanks for feedback, good to hear! Closing the issue for now.

**Closed by eknabevcc** 2022-11-11 10:27 UTC
