### ISSUE TITLE
Simulation does not stop even though a trigger is evaluated true

### ISSUE THREAD

**Issue by mschneider1711** [esmini/esmini#211] opened 2022-01-18 14:44 UTC
I am playing around with the new conditions which are added with OpenScenario V1.1 (THW and TTC).
I got a scenario in which my ego collides with a challenger vehicle. I included a stop trigger to the storyboard to evaluate true if the ego has a collision. Even though the log.txt shows that the collision was recognized the simulation continues.
I think this is the relevant information for this.

`1.876: Collision between EgoVehicle and ChallengingVehicle_945` this is from the log.txt

I have several stop triggers added and from my understanding, they are connected with a logical OR. So if one evaluates to true the trigger should be acting. I hope you can help me with this

> </Story>
        <StopTrigger>
            <ConditionGroup>
                <Condition name="Time headaway trigger" delay="0" conditionEdge="rising">
                    <ByEntityCondition>
                        <TriggeringEntities triggeringEntitiesRule="any">
                            <EntityRef entityRef="EgoVehicle"/>
                        </TriggeringEntities>
                        <EntityCondition>
                            <TimeHeadwayCondition entityRef="EgoVehicle" value="5" relativeDistanceType="longitudinal" coordinateSystem="road" freespace="true" rule="lessThan"/>
                        </EntityCondition>
                    </ByEntityCondition>
                </Condition>
            </ConditionGroup>
            <ConditionGroup>
                <Condition name="Time to collision trigger" delay="0" conditionEdge="rising">
                    <ByEntityCondition>
                        <TriggeringEntities triggeringEntitiesRule="any">
                            <EntityRef entityRef="EgoVehicle"/>
                        </TriggeringEntities>
                        <EntityCondition>
                            <TimeToCollisionCondition value="15" relativeDistanceType="longitudinal" coordinateSystem="road" freespace="true" rule="lessThan">
                                <TimeToCollisionConditionTarget>
                                    <EntityRef entityRef="EgoVehicle"/>
                                </TimeToCollisionConditionTarget>
                            </TimeToCollisionCondition>
                        </EntityCondition>
                    </ByEntityCondition>
                </Condition>
            </ConditionGroup>
            <ConditionGroup>
                <Condition name="Reach position condition" delay="0" conditionEdge="rising">
                    <ByEntityCondition>
                        <TriggeringEntities triggeringEntitiesRule="any">
                            <EntityRef entityRef="EgoVehicle"/>
                        </TriggeringEntities>
                        <EntityCondition>
                            <ReachPositionCondition tolerance="1">
                                <Position>
                                    <WorldPosition x="335.6357" y="-67.9807" z="0" h="2.216713012360714" p="0" r="0"/>
                                </Position>
                            </ReachPositionCondition>
                        </EntityCondition>
                    </ByEntityCondition>
                </Condition>
            </ConditionGroup>
            <ConditionGroup>
                <Condition name="Collision trigger" delay="0" conditionEdge="rising">
                    <ByEntityCondition>
                        <TriggeringEntities triggeringEntitiesRule="any">
                            <EntityRef entityRef="EgoVehicle"/>
                        </TriggeringEntities>
                        <EntityCondition>
                            <CollisionCondition>
                                <EntityRef entityRef="EgoVehicle"/>
                            </CollisionCondition>
                        </EntityCondition>
                    </ByEntityCondition>
                </Condition>
            </ConditionGroup>
        </StopTrigger>
    </Storyboard>
</OpenSCENARIO>

**Comment by mschneider1711** [comment] 2022-01-18 14:47
Maybe a small addition.
As one can see multiple triggers evaluate to true but the scenario still runs until the `reach position condition` , as i call it, is "reached".

> 25.650: Time headaway trigger == true, HWT: 0.00 < 5.00, edge rising
25.650: Triggering entity 0: EgoVehicle
25.650: Time to collision trigger == false, TTC: Inf < 15.00, edge rising
25.650: Reach position condition == true, distance 0.90 < tolerance (1.00), edge: rising
25.650: Triggering entity 0: EgoVehicle
25.650: collision 0 between EgoVehicle and EgoVehicle
25.650: Collision trigger == true edge: rising
25.650: Triggering entity 0: EgoVehicle
25.650: Trigger  ------------------------------------------------/

**Comment by eknabevcc** [comment] 2022-01-18 17:23
You got it right regarding the boolean logic, conditionGroups are OR:ed (while conditions within a groups are AND:ed). 

But then, one issue I think is that you have EgoVehicle both as trigger and reference object. 
Another issue is the tricky rising edge. E.g. the time to collision < 15 is already fulfilled when simulation starts, hence there will not be an edge, which happens when the condition flips between True/False.

You can check and play with this scenario in which I added your stop conditions slightly modified. I think they work as intended.
[stop_conditions.xosc.txt](https://github.com/esmini/esmini/files/7891109/stop_conditions.xosc.txt)

Put it in resources/xosc and run it from esmini root as:
./bin/esmini --window 60 60 800 400 --osc ./resources/xosc/stop_conditions.xosc

**Comment by mschneider1711** [comment] 2022-01-19 08:06
Thank you very much for the explanation it works fine. 
However, i think the main problem was that I use the EgoVehicle both as trigger and reference object. In my Scenario I have many challenger vehicles let's just say 20. Do I have to add as many condition groups for each possible collision between a challenger vehicle and the ego? I thought maybe there is workaround so it triggers if any car crashes with the ego.

**Comment by mschneider1711** [comment] 2022-01-19 08:22
Alright, that helps a lot. Thank you very much!

**Comment by eknabevcc** [comment] 2022-01-19 08:34
Good to hear 👍. Thanks for quick feedback. I close the issue now. Please just re-open of you find more questions.

**Comment by mschneider1711** [comment] 2022-01-19 09:21
I have another question related to this topic. Is it possible to add conditions which work as the above but do not impact the simulation. For example a collision is detected but the simulation does not stop and continues running and in the end I would like to check the log.txt and see all events which took place in my scenario. Because of the different conditions I use there are many different possible outcomes and I would like to see them to kind of benchmark my dataset I am using.

**Comment by mschneider1711** [comment] 2022-01-19 09:24
Moreover, I am really new to github and I think i can not re-open an issue which is closed by the collaborator:

https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github

**Comment by eknabevcc** [comment] 2022-01-19 09:29
Ah, I see, I just assumed a reported could re-open his/her own issue. Good to know. 

Regarding the question:
You have good timing. From v2.19.1 there is global collision detection. See [release notes](https://github.com/esmini/esmini/blob/master/release_notes.md#2022-01-09-version-2191).

This means that you can skip all collision conditions, and just check the log file. Hopefully this is what you need.

**Comment by mschneider1711** [comment] 2022-01-19 09:35
Yeah, kind of it fixes the problem for the collision. However, I use a thw and ttc as well. It would be nice to just let the whole scenario play through and afterward see which events took place if this is possible. So that one condition does not end the simulation but evaluates to true in the log.txt. I don't know if OpenScenario supports this use case.

**Comment by eknabevcc** [comment] 2022-01-19 10:09
Well, the simplest solution I see is to just add empty events like in the example (same as previous): [Unittest/xosc/test-collision-detection.xosc](https://github.com/esmini/esmini/blob/aadd9edf511d5aa0a2f5ad3d00178e0cc199d698/EnvironmentSimulator/Unittest/xosc/test-collision-detection.xosc#L115). 
There are collision conditions that will be logged (like all conditions) but no action is taken:
```xml
<Event name="CollisionEvent" priority="overwrite" maximumExecutionCount="-1">
     <Action name="CollisionAction"/>
     <StartTrigger>
...
```
This is the only solution I see. Only collision detections are automatically evaluated, not TTC, HWT and other measurements (I can imaging many, just think about all relative distances, velocity and so on...). Users can use conditions for those, which is the OpenSCENARIO way to go.

**Comment by mschneider1711** [comment] 2022-01-19 12:00
That's a good workaround I guess. Thank you for your answers!

**Comment by mschneider1711** [comment] 2022-01-19 13:37
I tested even more by now and I would like to inform you that it does not work very well. The performance is really struggling and instead of a fluent "video", the simulation is more like jumping from frame to frame (I don't know maybe 2-3 FPS). This is just for your information because it is a very special use case and one can not solve this so easily I think.

**Comment by eknabevcc** [comment] 2022-01-19 13:54
Could you share some more details? For example, what conditions are involved and how many vehicles. Is it all-to-all checks for collisions or only from Ego-to-all?
The very best would be if you could share the scenario! Then we could have a look and potentially find, understand and fix any obvious bottlenecks. 
It may of course be that the number of "challengers" simply are high, resulting in many required calculations. But it would be interesting to investigate, for which we need the scenario. So please share it if possible.

**Comment by mschneider1711** [comment] 2022-01-19 14:13
Okay, due to company regulations It would be awesome if you would give me an e-mail I could send an example to.

**Comment by eknabevcc** [comment] 2022-01-19 14:43
Understood and respected. You can find it here: https://sites.google.com/view/simulationscenarios (at the bottom of the page).
If possible you could remove any sensitive details from the scenario. In this case I think it's the bulk of stuff, like actions or rather conditions that is of interest.

**Comment by mschneider1711** [comment] 2022-01-19 15:09
I sent to you the example. I am encountering this problem since I added many condition groups to the stop trigger of the storyboard. In the past, the high amount of follow trajectory actions was never a problem.

**Comment by eknabevcc** [comment] 2022-01-19 15:14
I understand. I hope we can find something that can improve performance for this kind of scenarios. Will try to look into it in the next couple of days.

**Comment by eknabevcc** [comment] 2022-01-23 17:20
Thanks for providing the scenario. It really helps to understand issues and get ideas for solutions. I’ve sent some specific feedback via mail, but there are multiple aspects that I want to highlight here, as they are of general interest, and non sensitive. 
Actually, this issue has already resulted in two code changes to boost performance. The changes (see below) are merged on master and will be included in next release. Let us know if you need a release asap.

1. Global collision detection
Realizing that for scenarios with large amount of entities the global all-to-all collision detection may influence the performance notably, we now changed default behavior of esmini (commit a43e37acf94ac5a05038129e6e37ce09f8967038). By default the collision detection will be disabled. It can be enabled from command line with flag `—collision` or via API SE_CollisionDetection(bool). 
So like in this case where only collision between Ego and others are of interest, it makes sense to make use of CollisionCondition instead of the global collision detection.

2. Filter conditions, or multiple “level of detail”
The TTC and HeadwayTime are examples of conditions that require some detailed measurements and calculations. For most entities it’s overkill since they are far away, only a few are typically close to the Ego vehicle at any given time. We can utilize AND/OR combinations of conditions. By putting multiple conditions within one and same ConditionGroup they all need to be true to trig. 
Shooting a suggestion from the hip: First skip all entities at lateral distance > 4 meter (RelativeDistanceCondition/lateral), then skip all entities at longitudinal distance > 50 m (RelativeDistanceCondition/longitudinal). Finally evaluate the TTC/HWT condition.
Something like this generic example:
```xml
<ConditionGroup>
    <Condition name="LateralDistTrigger_1" delay="0" conditionEdge="none">
        <ByEntityCondition>
            <TriggeringEntities triggeringEntitiesRule="any">
                <EntityRef entityRef="EgoVehicle"/>
            </TriggeringEntities>
            <EntityCondition>
                <RelativeDistanceCondition value="4.0" freespace="false" entityRef="NPCVehicle_1" rule="lessThan" relativeDistanceType="lateral" coordinateSystem="entity"/>
            </EntityCondition>
        </ByEntityCondition>
    </Condition>
    <Condition name="LongitudinalDistDistTrigger_1" delay="0" conditionEdge="none">
        <ByEntityCondition>
            <TriggeringEntities triggeringEntitiesRule="any">
                <EntityRef entityRef="EgoVehicle"/>
            </TriggeringEntities>
            <EntityCondition>
                <RelativeDistanceCondition value="50.0" freespace="false" entityRef=" NPCVehicle_1" rule="lessThan" relativeDistanceType="longitudinal" coordinateSystem="entity"/>
            </EntityCondition>
        </ByEntityCondition>
    </Condition>
    <Condition name="Time headway trigger_1" delay="0" conditionEdge="rising">
        <ByEntityCondition>
            <TriggeringEntities triggeringEntitiesRule="any">
                <EntityRef entityRef="EgoVehicle"/>
            </TriggeringEntities>
            <EntityCondition>
                <TimeHeadwayCondition entityRef=" NPCVehicle_1" value="$0.7" relativeDistanceType="longitudinal" coordinateSystem="entity" freespace="true" rule="lessThan"/>
            </EntityCondition>
        </ByEntityCondition>
    </Condition>
<ConditionGroup>
```
For example, if the lateral distance is > 4 meter, the remaining two conditions will be skipped. Hence saving performance. The two first conditions are “cheap” performance wise. And only rough result is needed, hence the freespace="false" (ref point to ref. point) which radically improves performance compared to freespace=”true” which will calculate exact (corner/corner or corner/side) distance between oriented bounding boxes.

Actually, up to now, esmini did always evaluate ALL conditions, even in an AND group. But by commit  01d0f5f4ef4be282eb587885009f411bea72eb3f a condition group will return as soon as one condition is found false. Exception for conditions with delay, which is a special case.

3. Another potential performance boost is the flag `--disable_stdout` which will prevent log output to console/terminal. But this probably only has effect when there are extremely frequent log messages. 

4. Finally, as you proposed yourself, from version 2.20.0 it’s better to utilize the Add/DeleteEntity actions than VisibilityAction for vehicles that enters and exits the scenario.

**Comment by mschneider1711** [comment] 2022-01-24 11:20
Hi Emil, 
thank you very much for the detailed analysis and the proposed solutions. I am very excited to try it as soon as possible. As you mentioned above it would be awesome if you could provide the new release because I am not familiar with the process to create esmini by myself with the new commits. That would help a lot.

**Comment by eknabevcc** [comment] 2022-01-25 07:34
Release [v2.20.2](https://github.com/esmini/esmini/releases/tag/v2.20.2) available.
Please test and report how it works.

**Comment by mschneider1711** [comment] 2022-01-25 07:59
I just tested it and it runs very smoothly. All proposed solutions and additions work fine as well. Again thank you very much for your help.

**Comment by eknabevcc** [comment] 2022-01-25 08:29
That's really good news. Thanks for reporting the issue. We actually learned, and now shared, some lessons how to deal with large (in terms of #entities) scenarios. And esmini was improved as well.
Closing the issue.

**Comment by eknabevcc** [comment] 2022-01-25 13:13
We found (or rather, you found :)) an issue in esmini interpretation of the EntityAction.
The entityRef should be an attribute to the EntityAction (parent) element, not AddEntityAction or DeleteEntityAction. Its obvious in the [documentation](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.1.1_Model_Documentation/modelDocumentation/content/EntityAction.html). It was me reading sloppy.

Anyway, it should now be fixed (both application code and example scenario) in esmini by commit https://github.com/esmini/esmini/commit/669ced4b10bd347300d926ad532af34172d498ed

I'll keep the issue open until release.

**Comment by mschneider1711** [comment] 2022-01-25 13:29
Thank you very much for the fix

**Comment by eknabevcc** [comment] 2022-01-26 07:03
Release [v2.20.3](https://github.com/esmini/esmini/releases/tag/v2.20.3) available. 
Closing the issue.

**Closed by eknabevcc** 2022-01-26 07:03 UTC
