### ISSUE TITLE
TimeHeadwayCondition does not trigger

### ISSUE THREAD

**Issue by arauschert** [esmini/esmini#23] opened 2020-06-26 11:01 UTC
When using the TimeHeadwayCondition it does not trigger.

By looking at the code, I assume the problem is that when the relative distance between the leading object and the following object is calculated, the result has a wrong sign. This leads to an abort in the calculation because it is assumed that the leading object is behind the following object, which is invalid (OSCCondition.cpp, line 367 ff.):

// Headway time not defined for cases:
//  - when target object is behind 
//  - when object is still or going reverse 
if (rel_dist < 0 || object_->speed_ < SMALL_NUMBER)

In file OSCCondition.cpp, line 356:
triggering_entities_.entity_[i].object_->pos_.Delta(object_->pos_, diff);

The minuend and subtrahend need to be switched, leading to something like:
object_->pos_.Delta(triggering_entities_.entity_[i].object_->pos_, diff);

Example:
leading object (triggering_entities) is at s = 500
following object (object_) is at s = 400
Then RoadPath goes from triggering_entities (s=500) to object_ (s=400)
diff (and therefore rel_dist) is -100

**Comment by eknabe** [comment] 2020-06-30 05:55
HeadwayTime (HWT) is a tricky topic that has been discussed multiple times. The two major questions have been:

1. Does it matter whether from which of two entities the measurement is done? Consider a situation where vehicle B is in front of A, both A and B moving forward. HWT is clearly defined for vehicle A: It is the time gap to B’s current position. But from vehicle B it seems strange to measure HWT to a vehicle behind it. So in esmini we decided that HWT is undefined for entities behind (negative distance).
2. What is triggering entity and reference entity in HWT calculation? The OSC 1.0 reference documentation says: “Condition based on the headway time between a triggering entity/entities and a reference entity…” and “EntityRef = Reference entity to which the time headway is computed.” So, in the example above, if A is the triggering entity and B (lead) is the reference entity, the measurement should be from A to B, and all should be good.

Does it make sense? In that case perhaps the entities in your example could switch roles, so that the leading vehicle is the reference entity and the following object is the triggering entity? That’s how we implemented the cut-in example scenario.

All that said, I realize that the description (in code comments) for the Delta() method was wrong and misleading. The Delta method will actually calculate the s-distance from the current position object to another reference position (pos_b), in effect subtracting the current position from the reference position (pos_b). The comment said that the pos_b is subtracted from the current position, which was wrong, and the description has now been corrected.

Also the dLaneID and dT (lateral distance) was calculated in the wrong way, and has now been fixed (commit [f37e2dd](https://github.com/esmini/esmini/commit/f37e2dd1362861a8c3171237afeb33acb66a6387)).

So, thanks a lot for pointing out the issue, which resulted in alignment of calculations and clarification of description!

**Comment by arauschert** [comment] 2020-06-30 06:55
Thanks for the quick reply.
When taking a look at the calculations in OSCCondition.cpp, I assume object_ (A) must be the vehicle behind / the reference entity because its speed is used to calculate the time gap.
I think for the cut-in scenario the condition triggers because vehicle B has a similar speed than A. I found the problem by making B static/not moving. so speed of B is 0.

**Comment by eknabevcc** [comment] 2020-06-30 14:46
You're completely right. The time gap is calculated based on reference object's speed - and that's wrong I would say. 
Aligning to the OSC 1.0 description and to the example above, the time gap should be calculated based on the triggering entity (which would be A, =vehicle behind, in the example). And by fixing this "bug", (commit [fd2c8f2](https://github.com/esmini/esmini/commit/fd2c8f2b47015b68b933e5ac38fdd77b2896981f))  I hope we're fine. I also added a scenario "slow-lead-vehicle.xosc" that hopefully clarifies for future users. 

I think the root cause of bugs is that original code had the roles swapped. 

I realize there are still some aspects to consider. E.g. By adding actors to the ManeuverGroup, you in effect assign the ability to brake for the slow vehicle to them all. However it's a bit more tricky to assign the ability to brake for many slow vehicles (e.g. you can't assign the TimeHeadwayCondition/entityRef role to multiple entities) - but perhaps there are ways to solve that too...

**Comment by arauschert** [comment] 2020-06-30 15:35
Yes, using the triggering_entities_´ speed to calculate the time gap is the other solution that fixes the issue.
So the issue can be closed from my POV.

Just a remark:
If you have a 1:1 relation then you can always write the condition in a way, so you get a working scenario (which was my use-case, so I´m fine). But if you have a 1:n relation with multiple triggering entities, they cannot be ahead of the reference entity.
The OSC documentation sadly doesn´t mention clearly which entity shall be the leading entity and which one shall be the entity behind. Maybe the documentation also tries to leave this up to the user, so you can model 1:n relations in both directions (using a negative time headway value if necessary)?

**Comment by eknabevcc** [comment] 2020-07-01 14:41
I agree. OSC 1.0 does not say explicitly whether the triggering entity should be behind or in front. However, the phrase "Reference entity to which the time headway is computed" from the reference documentation makes me lean towards that the reference vehicle is in front of the triggering one. 
Anyway, I think, as you hint, there is a potential to make this clearer and/or more flexible, for example by supporting negative headway values. And provide examples on how to scale 1:n/n:1. Could be a task for 1.X...
I close this issue for now, we can open again if needed.

**Closed by eknabevcc** 2020-07-01 14:41 UTC
