### ISSUE TITLE
[EntityCondition/SpeedCondition]  conflict with the [external controller/ghost on]

### ISSUE THREAD

**Issue by jurriya** [esmini/esmini#210] opened 2022-01-14 06:44 UTC
I have one osc file which uses the external controller with a ghost vehicle.
It can be executed in the esmini2.16.1 ,but can't be executed from 2.17.1.
I find the [EntityCondition/SpeedCondition] defined in the StartTrigger of ManeuverGroup has a confliction with the [external controller/ghost on], but no error message in the cmd window. 
Could you help to see what's the reason to cause the issue?

[osc.zip](https://github.com/esmini/esmini/files/7868340/osc.zip)

**Comment by eknabevcc** [comment] 2022-01-15 11:10
Many thanks for reporting this issue. 
The provided scenarios and explanation is greatly appreciated. Thanks to these it tool only minutes to identify the root cause.
Which actually was two:
1. A bug assuming the ghost condition to be associated with an event. So for act conditions the event was NULL causing the crash. Fixed now.
2. When using ghost, some conditions are transferred from Ego (or "parent" of the ghost) to the ghost. This set of conditions is now extended from only:
\- CollisionCondition 
\- ReachPositionCondition 
\- TraveledDistanceCondition 
to also include:
\- SpeedCondition
\- EndOfRoadCondition
\- OffRoadCondition
\- StandStillCondition 
should be most except for the relative ones.

Fixed by commit https://github.com/esmini/esmini/commit/bce00181f2853abcd2e4852652e8601ea67f60e9
It's merged on master and will be part of next release.

Please test when possible and report if it works better. Can you build esmini yourself or do you need a release?

**Comment by jurriya** [comment] 2022-01-17 01:02
Thank you from the bottom of my heart and admiration for such a quick response and correspondence.
I have build the master branch and it works well.
Thank you again from the bottom of my heart.

**Comment by eknabevcc** [comment] 2022-01-17 07:55
Excellent, thanks for quick test and feedback.
It's included in release [2.19.3](https://github.com/esmini/esmini/releases/tag/v2.19.3).
Closing the issue.

**Closed by eknabevcc** 2022-01-17 07:55 UTC
