### ISSUE TITLE
Add SE_RegisterStoryBoardElementStateChangeCallback to esminiLib

### ISSUE THREAD

**Issue by mickmack1213** [esmini/esmini#311] opened 2022-07-29 08:09 UTC
I'm currently working on a project where I want to simulate and monitor many OpenSCENARIO Files automatically via a python-script.

For this a better way to know when the simulation has finished would be great. Currently I'm tracking if any events were started and did not finish, but that's not really great...

So if I could monitor the States of the StoryboardElements would be pretty nice.

I'd propose a callback signature something like:
`void (*fnPtr)(const char* name, ElementType type, State state)`

And I would place the call to the callback into `StoryBoardElement::SetState`.

What do you think of this idea? Would you be willing to change the public API? If yes I can make a push request and implement it.

**Comment by eknabevcc** [comment] 2022-08-08 06:22
This sounds like a good idea. However, to my understanding it is similar to the already existing callback: [SE_RegisterEventCallback](https://github.com/esmini/esmini/blob/8be51cc09fd44af3dcef3e3dcc7dbffa18dfbca5/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L849) - which was kindly added by @cfschaller in PR #249.

To my understanding and in spite of its name it handles all types of StoryBoardElement types, not only events. It reports back timestamp and a flag indicating whether the scenario element was started or ended.

Two difference I can see are: 1. Your proposal explicitly reports the element type. 2. The current implementation includes timestamp (instead).
Another difference is where (and in effect when) the callback happens.

Before implementing something similar or overlapping, can you please review that existing functionality to see if it covers your need or not?

**Comment by mickmack1213** [comment] 2022-08-08 13:17
Hmm, yeah it is similar, but I think I have to disagree with you, the current implementation does not provide this capability :thinking: 

At least if I scan for usages of the callback in CLion it only shows the following and all other matches with plain text search for `eventCallback` don't seem to do this also.

![grafik](https://user-images.githubusercontent.com/20105925/183418709-8f626dfc-8819-4151-b6ce-3218b671bb76.png)

It is true that this will work for all classes inheriting from `Event`, but for many StoryBoardElement types that's not the case. And I don't think it's good to change that.

My experience, if not really great but I did a few tests with the python interface, also showed, that those callbacks are only triggered for events. I put a log below, the output of my EventCallback is marked with `####` and see how no event is triggered for any state change of `MySequence` or `MyAct`

```
0.100: Trigger /------------------------------------------------
0.100: no name SimulationTimeCondition == true, 0.1000 > 0.00 edge: rising
0.100: Trigger  ------------------------------------------------/
0.100: MySequence standbyState -> startTransition -> runningState
0.100: MyAct standbyState -> startTransition -> runningState
1.718: Trigger /------------------------------------------------
1.718: MyStartCondition1 == true, rel_dist: 5.85 > 5.00, edge: rising
1.718: Triggering entity 0: A1
1.718: Trigger  ------------------------------------------------/
#### 1.718: EventCallback stop b'MyLaneChangeRightEvent'
1.719: MyLaneChangeRightAction standbyState -> startTransition -> runningState
1.719: MyLaneChangeRightEvent standbyState -> startTransition -> runningState
#### 3.741: EventCallback start b'MyLaneChangeRightEvent' 
3.741: MyLaneChangeRightEvent complete after 1 execution
3.742: MyLaneChangeRightAction runningState -> endTransition -> completeState
3.742: MyLaneChangeRightEvent runningState -> endTransition -> completeState
3.742: Trigger /------------------------------------------------
3.742: MyStartCondition2 == true, element: MyLaneChangeRightAction state: COMPLETE, edge: rising
3.742: Trigger  ------------------------------------------------/
#### 3.742: EventCallback stop b'MyLaneChangeLeftEvent'
3.842: MyLaneChangeLeftAction standbyState -> startTransition -> runningState
3.842: MyLaneChangeLeftEvent standbyState -> startTransition -> runningState
#### 5.767: EventCallback start b'MyLaneChangeLeftEvent' 
5.767: MyLaneChangeLeftEvent complete after 1 execution
5.768: MyLaneChangeLeftAction runningState -> endTransition -> completeState
5.768: MyLaneChangeLeftEvent runningState -> endTransition -> completeState
5.768: MySequence complete after 1 execution
5.868: MySequence runningState -> endTransition -> completeState
```

----

Now my thoughts on the different signature:

As StoryboardElement is a rather basic base class, the exact type might be really interesting for the users (It is, at least for me).

And getting the timestamp would be nice, but will get kinda tricky or hacky, as the information is currently not available in the `StoryBoardElement::SetState` method. And getting it there seems tough. While requesting StateTransitions the timestamp is passed as a parameter, but for actually setting the state not time information is passed. 

Changing this and passing time information to the `StoryBoardElement::SetState` is not easy. SetState is called from `StoryBoardElement::UpdateState` and this function is overloaded and used all over the place. 

I'm not confident to get the time in bug free on the first try with all those specializations.

**Comment by eknabevcc** [comment] 2022-08-08 14:10
I agree. After looking closer I also see that only events are considered.

So yes, I think it makes sense to add your proposed functionality. 

Regarding timestamp. You can skip it, at least for a start. I made a [test case](https://github.com/esmini/esmini/blob/afbc7a16e636182675ee314cb4dca80456151367/EnvironmentSimulator/Unittest/ScenarioEngineDll_test.cpp#L3298) to verify that the time returned by SE_GetSimulationTime() is the same as would have been supplied in the callback (making that argument not crucial).

Did I understand correct that except for the timestamp argument you'd like to do the implementation? In that case, please provide via pull request. 👍

And in dialog with @cfschaller perhaps the current event callback implementation can be removed to avoid overlapping/obsolete functionality. I'll have him check the PR as well.

**Comment by eknabevcc** [comment] 2022-08-09 07:37
Added [a test case](https://github.com/esmini/esmini/blob/ecde4f2a08432ccd8c8d13d53312e6a67aa959dd/EnvironmentSimulator/Unittest/ScenarioEngineDll_test.cpp#L3356) to 1: avoid regression of the feature and 2: to show how it works

@cfschaller FYI: This feature has been merged. It's similar to your event callback, but extends to all element types and states. It's lacking the time, but it can be retrieved via API so I don't think it's crucial. Do you think we can remove the event callback to slim the code, or you prefer to keep it?

**Comment by cfschaller** [comment] 2022-08-09 07:41
@eknabevcc I suggest the following: We will try the new feature with the next official release and if it works (which it should) we will no longer need the old callback and I will create a PR to remove it. Does that work for you?

**Comment by eknabevcc** [comment] 2022-08-09 07:53
@cfschaller That sounds like a perfect plan!

**Comment by mickmack1213** [comment] 2022-08-09 22:11
Hmm only one thing I have in mind:

The current callback is called while requesting the state change and my new one is called during execution of the state change.

If this might be an issue for a relying program, I don't know.

Your call. I'm fine with both.

**Comment by cfschaller** [comment] 2022-08-22 07:55
Hi @eknabevcc,
sorry to bother you again: is there a plan on when the next "official" release is going to be?
We can also use a custom build to test this if necessary.

**Comment by eknabevcc** [comment] 2022-08-22 14:07
Tomorrow or Wednesday likely.

**Comment by eknabevcc** [comment] 2022-08-24 14:23
[v2.26.0](https://github.com/esmini/esmini/releases/tag/v2.26.0) released

**Comment by cfschaller** [comment] 2022-11-03 13:09
Hi everyone,

we finally got to test the new functionality.

@eknabevcc From our side it is fine to remove the old callback (SE_RegisterEventCallback). 
As @mickmack1213 pointed out there is just a minor difference: the old callback is called when requesting the state change, the new one when executing the state change (i.e. one simulation step later). However, for our use case (and presumably similar usages), either of the two is fine.

If everyone agrees, I can create a PR to remove the old callback.

**Comment by eknabevcc** [comment] 2022-11-03 17:36
Hi @cfschaller, I suggest we remove the old one as you propose. Since the overlap of the newer is almost 100%.
Your pull request for the removal would be appreciated,

**Comment by eknabevcc** [comment] 2022-11-04 16:21
Thanks a lot for the pull request (#344)!
Now we can close this issue.

**Closed by eknabevcc** 2022-11-04 16:21 UTC
