### ISSUE TITLE
Combine SynchronizeAction with FollowTrajectoryAction

### ISSUE THREAD

**Issue by johannesWen** [esmini/esmini#48] opened 2020-10-29 10:08 UTC
Hello everybody,

I am trying to generate a Euro NCAP CPTA (Car-to-Pedestrian-Turnig-Adult) scenario.

![grafik](https://user-images.githubusercontent.com/57130737/97552335-6b5dc280-19d4-11eb-8bde-795c49af5dd3.png)

Therefore, I use two FollowTrajectoryActions (Ego & Target). For the Ego vehicle, this works perfect as steering input. 
My question is now. Is it possible to synchronize the Target trajectory to the Ego trajectory? So that the two actors meet at the crash point with the desired speed.
When I try to implement this scenario, I get the error that a road network path between the master and slave vehicle is required. So, is the SynchAction only possible for lanes?

Thank you for your help.
BR,
Johannes

**Comment by eknabevcc** [comment] 2020-11-02 11:49
Great finding! This is a use case we simply missed, combining synchronizeAction with followTrajectoryAction. Currently the action only tries to find a valid path to the target position (separate for master and action object) along the road network and then measure the (longitudinal) length of the paths.

Definitely it should work for trajectories as well. We will look into it and see if we can find a solution. 

Thanks for reporting the issue in a very clear way!

**Comment by eknabevcc** [comment] 2020-11-02 14:59
The issue hopefully solved by commit [d217bb9](https://github.com/esmini/esmini/commit/d217bb9bd5d8378adcf0b5d5ab5a520d9d844cd4). 

The strategy is now: If object is following a trajectory, then use euclidean distance (x, y world coordinates). Else if road network path found, calculate distance along that route. Otherwise, give up.

So, in your use case the first case should be applied. but it should also be OK to have a mix, e.g. vehicle following a route (longitudinal distance along road path to target) and pedestrian following a trajectory (x, y distance to its target).

By the way, I added a scenario file: [pedestrian_traj_synch.xosc](https://github.com/esmini/esmini/blob/master/resources/xosc/pedestrian_traj_synch.xosc) showing synchronizeAction with very simple trajectories, just as example.

Please test and let me know if there are still issues.

**Comment by johannesWen** [comment] 2020-11-03 08:10
Thank you, Emil, for the quick implementation!
I did some tests with my CPTA scenario and it worked perfectly. 👍 
BR, Johannes


![CPTA](https://user-images.githubusercontent.com/57130737/97961114-f6fb9880-1db2-11eb-86bf-7ba2872c69ea.gif)

**Comment by eknabevcc** [comment] 2020-11-03 09:41
Thanks Johannes for the issue report and good news feedback – including a video! (that’s a record 🙂)
BR Emil

**Comment by johannesWen** [comment] 2020-11-06 07:43
Hello again,

I did some tests with your [pedestrian_traj_synch.xosc](https://github.com/esmini/esmini/blob/master/resources/xosc/pedestrian_traj_synch.xosc) example and I analyzed the positions and speeds of the vehicles.
If I look at the positions at the synchronization point, it seems to be correct (x: 28.5, y: -7.5).
![grafik](https://user-images.githubusercontent.com/57130737/98335103-a4b1b600-2004-11eb-9f92-8969c6369ea6.png)

Concerning the speed of the target at the synchronization point, I noticed a deviation. In the scenario I use a final speed of 5 kph, but the target never reaches this speed. It looks like a steady state phase before the synch point. I tried different speed values, but I always get some deviation. Can you reproduce this behavior? 
![grafik](https://user-images.githubusercontent.com/57130737/98337066-52729400-2008-11eb-8de4-adc5d6a33194.png)
![grafik](https://user-images.githubusercontent.com/57130737/98337079-58687500-2008-11eb-8f52-5671822bb3a4.png)

BR,
Johannes

**Comment by eknabevcc** [comment] 2020-11-06 08:07
Good finding! I haven't looked that close before. I will look into it later, but after a quick glance at the [code I find a distance tolerance ](https://github.com/esmini/esmini/blob/6c914030a447b5de0e66e0e0defe56dd4bd877ef/EnvironmentSimulator/Modules/ScenarioEngine/OSCTypeDefs/OSCPrivateAction.cpp#L809)that might be the root cause:
```
	// Done when either of the vehicles reaches the destination
	if (dist < DISTANCE_TOLERANCE || (masterTimeToDest) < SMALL_NUMBER)
	{
		OSCAction::End();
	} 
```
I'm thinking that the action is terminated a bit too early due to this 0,5 meter tolerance. I'm thinking about another way of making sure that the destination is reached (the vehicle could potentially pass the target point by some small offset). Perhaps checking when distance rate changes from decreasing to increasing? But it's probably not bulletproof? Do you have any idea? If you can compile code maybe you could experiment, e.g. reduce the tolerance or test other criteria...

Anyway, thanks for reporting this. At least I think we should assign the target speed when the actions ends, even if it results in a slight "step". But it would be nice to come closer before ending the action!  As said, I will look closer within days. 👍

**Comment by johannesWen** [comment] 2020-11-07 11:48
I tried to reduce the DISTANCE_TOLERANCE value. This helps to get closer to the final speed, but as you said if this value is too small the Ego misses the Target and the action never ends.
I will play around a bit and if I have a good solution I will let you know.

**Comment by eknabevcc** [comment] 2020-11-08 12:16
Let's try a basic strategy, committed in [5a20b9b](https://github.com/esmini/esmini/commit/5a20b9b6b1ff4cf8c8b23e9b5012390872123070):

- Increase tolerance to 1m radius (from destination)
- Subtract the tolerance from distance calculations (so that when hitting the circle the distance has decreased to zero)
- End action whenever reaching the destination within tolerance, or
- End action if distance increases, indicating that destination has been passed on some distance > tolerance

I tried to illustrate three cases in picture below:
1. Normal case, the target is along the route. Action ends when hitting edge of tolerance circle. Distance reduced by 1m (=tolerance) , so user might need to compensate position of destination accordingly, if needed.
2. As 1, but the route is slightly off destination point, still within tolerance so action will end when hitting edge of circle.
3. Destination point is not within tolerance area from route /vehicle position. The check for distance increasing (from previously decreasing) will indicate destination passed and action will end.

![synch](https://user-images.githubusercontent.com/29146839/98464486-8514bc00-21c3-11eb-920c-24af7afd7a7e.png)

In case 3, current implementation will not set speed to specified target speed since it might be a large step depending on how far off the destination we are... It could be fixed with an additional action setting speed to desired value - if desired. 

It would be appreciated if you could test this with your use case and see how it works...
And let me know if you need a release.

**Comment by johannesWen** [comment] 2020-11-08 22:11
Good idea! I tested your strategy and for the target speed it looks pretty good now.
![grafik](https://user-images.githubusercontent.com/57130737/98484836-6c7fc280-2212-11eb-9dfe-ae43a9d7f731.png)

In my scenario the 1 m SYNCH_DISTANCE_TOLERANCE is a bit too big, because I use the exact intersection of the two trajectories and therefore the synchronization point should be hit more or less exactly.
![grafik](https://user-images.githubusercontent.com/57130737/98485109-3e9b7d80-2214-11eb-8602-3f596814b563.png)

So in my case a smaller SYNCH_DISTANCE_TOLERANCE value (e.g. 0.01 m) leads to a much better synchronization.  Is it possible to use a more adaptive synchronization distance? Maybe the minimum euclidean distance from the synchronization point to the trajectory plus a small epsilon.

**Comment by eknabevcc** [comment] 2020-11-09 06:20
Adaptive synch distance is a good idea. However in many cases it is not known the actual minimum distance. For example if we have an interactive driver in the loop, or if the time steps are large - the distance might vary more or less.
But you're proposal makes it clear that the use cases are very different and need of different tolerances. 
My best idea right now is to make tolerance an optional attribute, one each for object and target. Like this:

```
<SynchronizeAction masterEntityRef="Ego" >
     <TargetPositionMaster tolerance="1.0" >
         <WorldPosition x="$ESyncX" y="$ESyncY" h="3.3" />
     </TargetPositionMaster>    
     <TargetPosition tolerance="1.0" >
         <WorldPosition x="$PSyncX" y="$PSyncY" h="3.3" />
     </TargetPosition>    
     <FinalSpeed>
         <AbsoluteSpeed value="$PedestrianSpeed" />
     </FinalSpeed>
</SynchronizeAction>
```
This is now supported from commit [767be1c](https://github.com/esmini/esmini/commit/767be1c10f70fcdad55738e00b09b362a4d7c2ce). (default value = 1.0)
Please test and tell us what you think. If this could be a good solution I will propose it for OpenSCENARIO 1.1 (adding the two optional tolerance attributes to the standard).

**Comment by johannesWen** [comment] 2020-11-09 10:27
Yes, you are right, it might not be that easy but the optional attribute works quite well, too.
I think this would be a good proposal for version 1.1 of the OpenScenario standard, because the synchronization point is never 100% accurate.
I close this issue for now, thank you.

**Comment by eknabevcc** [comment] 2020-11-09 12:40
Good to hear!
I have filed a proposal for OSC 1.1. However, when I looked closer to the solution I couldn't find a way of making XSD backward compatible with the proposed syntax, so had to adjust the XSD a little bit into:

```
<xsd:complexType name="SynchronizeAction">
    <xsd:all>
        <xsd:element name="TargetPositionMaster" type="Position"/>
        <xsd:element name="TargetPosition" type="Position"/>
        <xsd:element name="FinalSpeed" type="FinalSpeed" minOccurs="0"/>
    </xsd:all>
    <xsd:attribute name="masterEntityRef" type="String" use="required"/>
    <xsd:attribute name="targetToleranceMaster" type="Double" use="optional"/> *
    <xsd:attribute name="targetTolerance" type="Double" use="optional"/> *
</xsd:complexType>

* added lines
```
So the syntax would be a little different, like this:
```
<SynchronizeAction masterEntityRef="Ego" targetToleranceMaster="1.0" targetTolerance="1.0" >
     <TargetPositionMaster>
         <WorldPosition x="$ESyncX" y="$ESyncY" h="3.3" />
     </TargetPositionMaster>    
     <TargetPosition>
         <WorldPosition x="$PSyncX" y="$PSyncY" h="3.3" />
     </TargetPosition>    
     <FinalSpeed>
         <AbsoluteSpeed value="$PedestrianSpeed" />
     </FinalSpeed>
</SynchronizeAction>
```

But let's keep as is for now. I'll let you know I we change.

Thanks again for excellent description of the issue and your need 👍

**Comment by eknabevcc** [comment] 2020-11-09 12:46
Let's open until we decided whether to go with first (position attributes) or second (action attributes) proposed syntax.

**Comment by eknabevcc** [comment] 2020-11-09 13:51
Ok, we took the decision to update according to proposal for OSC 1.1. Implementation updated in commit [c9ac0f1](https://github.com/esmini/esmini/commit/c9ac0f1dbfc48cafcf9edb8dd1f5469a3b55de73)
The slight change for you would be to move and rename the tolerance attributes, just according to the [comment above](https://github.com/esmini/esmini/issues/48#issuecomment-723988550).
I hope this will suit your needs just as good 👍

**Comment by eknabevcc** [comment] 2020-11-18 06:06
I'll close this now. Further Synchronize features discussed in [issue 51](https://github.com/esmini/esmini/issues/51)

**Closed by eknabevcc** 2020-11-18 06:06 UTC
